// Define the DC dictionary
let oaData = [
    {"Biome":"Arctic","Night_NC_DC":15,"Night_NC_Probability":"5%","Night_C_DC":16,"Night_C_Probability":"25%","Night_Total_Prob.":"30%","Day_NC_DC":16,"Day_NC_Probability":"10%","Day_C_DC":18,"Day_C_Probability":"15%","Day_Total_Prob.":"25%"},
    {"Biome":"Coastal","Night_NC_DC":16,"Night_NC_Probability":"5%","Night_C_DC":17,"Night_C_Probability":"20%","Night_Total_Prob.":"25%","Day_NC_DC":17,"Day_NC_Probability":"10%","Day_C_DC":19,"Day_C_Probability":"10%","Day_Total_Prob.":"20%"},
    {"Biome":"Desert","Night_NC_DC":16,"Night_NC_Probability":"5%","Night_C_DC":17,"Night_C_Probability":"20%","Night_Total_Prob.":"25%","Day_NC_DC":17,"Day_NC_Probability":"10%","Day_C_DC":19,"Day_C_Probability":"10%","Day_Total_Prob.":"20%"},
    {"Biome":"Farmland","Night_NC_DC":17,"Night_NC_Probability":"10%","Night_C_DC":19,"Night_C_Probability":"10%","Night_Total_Prob.":"20%","Day_NC_DC":17,"Day_NC_Probability":"15%","Day_C_DC":20,"Day_C_Probability":"5%","Day_Total_Prob.":"20%"},
    {"Biome":"Forest","Night_NC_DC":15,"Night_NC_Probability":"5%","Night_C_DC":16,"Night_C_Probability":"25%","Night_Total_Prob.":"30%","Day_NC_DC":16,"Day_NC_Probability":"10%","Day_C_DC":18,"Day_C_Probability":"15%","Day_Total_Prob.":"25%"},
    {"Biome":"Grassland","Night_NC_DC":16,"Night_NC_Probability":"5%","Night_C_DC":17,"Night_C_Probability":"20%","Night_Total_Prob.":"25%","Day_NC_DC":17,"Day_NC_Probability":"10%","Day_C_DC":19,"Day_C_Probability":"10%","Day_Total_Prob.":"20%"},
    {"Biome":"Hill","Night_NC_DC":16,"Night_NC_Probability":"5%","Night_C_DC":17,"Night_C_Probability":"20%","Night_Total_Prob.":"25%","Day_NC_DC":17,"Day_NC_Probability":"10%","Day_C_DC":19,"Day_C_Probability":"10%","Day_Total_Prob.":"20%"},
    {"Biome":"Jungle","Night_NC_DC":15,"Night_NC_Probability":"0%","Night_C_DC":15,"Night_C_Probability":"30%","Night_Total_Prob.":"30%","Day_NC_DC":16,"Day_NC_Probability":"5%","Day_C_DC":17,"Day_C_Probability":"20%","Day_Total_Prob.":"25%"},
    {"Biome":"Mountain","Night_NC_DC":14,"Night_NC_Probability":"5%","Night_C_DC":15,"Night_C_Probability":"30%","Night_Total_Prob.":"35%","Day_NC_DC":15,"Day_NC_Probability":"10%","Day_C_DC":17,"Day_C_Probability":"20%","Day_Total_Prob.":"30%"},
    {"Biome":"Open Water","Night_NC_DC":16,"Night_NC_Probability":"5%","Night_C_DC":17,"Night_C_Probability":"20%","Night_Total_Prob.":"25%","Day_NC_DC":16,"Day_NC_Probability":"10%","Day_C_DC":18,"Day_C_Probability":"15%","Day_Total_Prob.":"25%"},
    {"Biome":"Swamp","Night_NC_DC":14,"Night_NC_Probability":"5%","Night_C_DC":15,"Night_C_Probability":"30%","Night_Total_Prob.":"35%","Day_NC_DC":15,"Day_NC_Probability":"10%","Day_C_DC":17,"Day_C_Probability":"20%","Day_Total_Prob.":"30%"},
    {"Biome":"Underdark","Night_NC_DC":15,"Night_NC_Probability":"0.05","Night_C_DC":16,"Night_C_Probability":"0.25","Night_Total_Prob.":"0.3","Day_NC_DC":16,"Day_NC_Probability":"0.1","Day_C_DC":18,"Day_C_Probability":"0.15","Day_Total_Prob.":"0.25"},
    {"Biome":"Underwater","Night_NC_DC":16,"Night_NC_Probability":"0.05","Night_C_DC":17,"Night_C_Probability":"0.2","Night_Total_Prob.":"0.25","Day_NC_DC":17,"Day_NC_Probability":"0.1","Day_C_DC":19,"Day_C_Probability":"0.1","Day_Total_Prob.":"0.2"},
    {"Biome":"Urban","Night_NC_DC":17,"Night_NC_Probability":"0.05","Night_C_DC":18,"Night_C_Probability":"0.15","Night_Total_Prob.":"0.2","Day_NC_DC":18,"Day_NC_Probability":"0.1","Day_C_DC":20,"Day_C_Probability":"0.05","Day_Total_Prob.":"0.15"},
    {"Biome":"Wasteland","Night_NC_DC":14,"Night_NC_Probability":"0.05","Night_C_DC":15,"Night_C_Probability":"0.3","Night_Total_Prob.":"0.35","Day_NC_DC":15,"Day_NC_Probability":"0.1","Day_C_DC":17,"Day_C_Probability":"0.2","Day_Total_Prob.":"0.3"},
    {"Biome":"Woodland","Night_NC_DC":16,"Night_NC_Probability":"0.05","Night_C_DC":17,"Night_C_Probability":"0.2","Night_Total_Prob.":"0.25","Day_NC_DC":17,"Day_NC_Probability":"0.1","Day_C_DC":19,"Day_C_Probability":"0.1","Day_Total_Prob.":"0.2"}
]
// Define the Encounter Distance Dictionary
let oaEncounterDistance = [
    {"biome":"Arctic","number_of_dice":6,"number_of_sides":6,"multiplier":10},
    {"biome":"Coastal","number_of_dice":6,"number_of_sides":6,"multiplier":10},
    {"biome":"Desert","number_of_dice":6,"number_of_sides":6,"multiplier":10},
    {"biome":"Farmland","number_of_dice":6,"number_of_sides":6,"multiplier":10},
    {"biome":"Forest","number_of_dice":2,"number_of_sides":8,"multiplier":10},
    {"biome":"Grassland","number_of_dice":6,"number_of_sides":6,"multiplier":10},
    {"biome":"Hill","number_of_dice":2,"number_of_sides":10,"multiplier":10},
    {"biome":"Jungle","number_of_dice":2,"number_of_sides":6,"multiplier":10},
    {"biome":"Mountain","number_of_dice":4,"number_of_sides":10,"multiplier":10},
    {"biome":"Open Water","number_of_dice":5,"number_of_sides":10,"multiplier":10},
    {"biome":"Swamp","number_of_dice":2,"number_of_sides":8,"multiplier":10},
    {"biome":"Underdark","number_of_dice":2,"number_of_sides":6,"multiplier":10},
    {"biome":"Underwater","number_of_dice":1,"number_of_sides":6,"multiplier":10},
    {"biome":"Urban","number_of_dice":2,"number_of_sides":6,"multiplier":10},
    {"biome":"Wasteland","number_of_dice":2,"number_of_sides":10,"multiplier":10},
    {"biome":"Woodland","number_of_dice":2,"number_of_sides":8,"multiplier":10}
]
// COMBAT ENCOUNTER JSONs
    // Arctic
let arctic = [
    {"Encounter":"1 giant owl","roll":1,"Level":"1-4"},
    {"Encounter":"1d6+3 kobolds","roll":2,"Level":"1-4"},
    {"Encounter":"1d6+3 kobolds","roll":3,"Level":"1-4"},
    {"Encounter":"1d6+3 kobolds","roll":4,"Level":"1-4"},
    {"Encounter":"1d6+3 kobolds","roll":5,"Level":"1-4"},
    {"Encounter":"1d4+3 trappers (commoners)","roll":6,"Level":"1-4"},
    {"Encounter":"1d4+3 trappers (commoners)","roll":7,"Level":"1-4"},
    {"Encounter":"1d4+3 trappers (commoners)","roll":8,"Level":"1-4"},
    {"Encounter":"1 owl","roll":9,"Level":"1-4"},
    {"Encounter":"1 owl","roll":10,"Level":"1-4"},
    {"Encounter":"2d4 blood hawks","roll":11,"Level":"1-4"},
    {"Encounter":"2d4 blood hawks","roll":12,"Level":"1-4"},
    {"Encounter":"2d6 bandits","roll":13,"Level":"1-4"},
    {"Encounter":"2d6 bandits","roll":14,"Level":"1-4"},
    {"Encounter":"2d6 bandits","roll":15,"Level":"1-4"},
    {"Encounter":"2d6 bandits","roll":16,"Level":"1-4"},
    {"Encounter":"2d6 bandits","roll":17,"Level":"1-4"},
    {"Encounter":"1d3 winged kobolds with 1d6 kobolds","roll":18,"Level":"1-4"},
    {"Encounter":"1d3 winged kobolds with 1d6 kobolds","roll":19,"Level":"1-4"},
    {"Encounter":"1d3 winged kobolds with 1d6 kobolds","roll":20,"Level":"1-4"},
    {"Encounter":"The partially eaten carcass of a mammoth, from which 1d4 weeks of rations can be harvested.","roll":21,"Level":"1-4"},
    {"Encounter":"The partially eaten carcass of a mammoth, from which 1d4 weeks of rations can be harvested.","roll":22,"Level":"1-4"},
    {"Encounter":"The partially eaten carcass of a mammoth, from which 1d4 weeks of rations can be harvested.","roll":23,"Level":"1-4"},
    {"Encounter":"The partially eaten carcass of a mammoth, from which 1d4 weeks of rations can be harvested.","roll":24,"Level":"1-4"},
    {"Encounter":"The partially eaten carcass of a mammoth, from which 1d4 weeks of rations can be harvested.","roll":25,"Level":"1-4"},
    {"Encounter":"2d8 hunters tribal warriors","roll":26,"Level":"1-4"},
    {"Encounter":"2d8 hunters tribal warriors","roll":27,"Level":"1-4"},
    {"Encounter":"2d8 hunters tribal warriors","roll":28,"Level":"1-4"},
    {"Encounter":"2d8 hunters tribal warriors","roll":29,"Level":"1-4"},
    {"Encounter":"1 half-ogre","roll":30,"Level":"1-4"},
    {"Encounter":"1 half-ogre","roll":31,"Level":"1-4"},
    {"Encounter":"1 half-ogre","roll":32,"Level":"1-4"},
    {"Encounter":"1 half-ogre","roll":33,"Level":"1-4"},
    {"Encounter":"1 half-ogre","roll":34,"Level":"1-4"},
    {"Encounter":"1 half-ogre","roll":35,"Level":"1-4"},
    {"Encounter":"Single-file tracks in the snow that stop abruptly","roll":36,"Level":"1-4"},
    {"Encounter":"Single-file tracks in the snow that stop abruptly","roll":37,"Level":"1-4"},
    {"Encounter":"Single-file tracks in the snow that stop abruptly","roll":38,"Level":"1-4"},
    {"Encounter":"Single-file tracks in the snow that stop abruptly","roll":39,"Level":"1-4"},
    {"Encounter":"Single-file tracks in the snow that stop abruptly","roll":40,"Level":"1-4"},
    {"Encounter":"1d3 ice mephits","roll":41,"Level":"1-4"},
    {"Encounter":"1d3 ice mephits","roll":42,"Level":"1-4"},
    {"Encounter":"1d3 ice mephits","roll":43,"Level":"1-4"},
    {"Encounter":"1d3 ice mephits","roll":44,"Level":"1-4"},
    {"Encounter":"1d3 ice mephits","roll":45,"Level":"1-4"},
    {"Encounter":"1 brown bear","roll":46,"Level":"1-4"},
    {"Encounter":"1 brown bear","roll":47,"Level":"1-4"},
    {"Encounter":"1 brown bear","roll":48,"Level":"1-4"},
    {"Encounter":"1 brown bear","roll":49,"Level":"1-4"},
    {"Encounter":"1 brown bear","roll":50,"Level":"1-4"},
    {"Encounter":"1d6+1 orcs","roll":51,"Level":"1-4"},
    {"Encounter":"1d6+1 orcs","roll":52,"Level":"1-4"},
    {"Encounter":"1d6+1 orcs","roll":53,"Level":"1-4"},
    {"Encounter":"1 polar bear","roll":54,"Level":"1-4"},
    {"Encounter":"1 polar bear","roll":55,"Level":"1-4"},
    {"Encounter":"1d6 scouts","roll":56,"Level":"1-4"},
    {"Encounter":"1d6 scouts","roll":57,"Level":"1-4"},
    {"Encounter":"1 saber-toothed tiger","roll":58,"Level":"1-4"},
    {"Encounter":"1 saber-toothed tiger","roll":59,"Level":"1-4"},
    {"Encounter":"1 saber-toothed tiger","roll":60,"Level":"1-4"},
    {"Encounter":"A frozen pond with a jagged hole in the ice that appears recently made","roll":61,"Level":"1-4"},
    {"Encounter":"A frozen pond with a jagged hole in the ice that appears recently made","roll":62,"Level":"1-4"},
    {"Encounter":"A frozen pond with a jagged hole in the ice that appears recently made","roll":63,"Level":"1-4"},
    {"Encounter":"A frozen pond with a jagged hole in the ice that appears recently made","roll":64,"Level":"1-4"},
    {"Encounter":"A frozen pond with a jagged hole in the ice that appears recently made","roll":65,"Level":"1-4"},
    {"Encounter":"1 berserker","roll":66,"Level":"1-4"},
    {"Encounter":"1 berserker","roll":67,"Level":"1-4"},
    {"Encounter":"1 berserker","roll":68,"Level":"1-4"},
    {"Encounter":"1 ogre","roll":69,"Level":"1-4"},
    {"Encounter":"1 ogre","roll":70,"Level":"1-4"},
    {"Encounter":"1 griffon","roll":71,"Level":"1-4"},
    {"Encounter":"1 griffon","roll":72,"Level":"1-4"},
    {"Encounter":"1 druid","roll":73,"Level":"1-4"},
    {"Encounter":"1 druid","roll":74,"Level":"1-4"},
    {"Encounter":"1 druid","roll":75,"Level":"1-4"},
    {"Encounter":"3d4 refugees (commoners) fleeing from orcs","roll":76,"Level":"1-4"},
    {"Encounter":"3d4 refugees (commoners) fleeing from orcs","roll":77,"Level":"1-4"},
    {"Encounter":"3d4 refugees (commoners) fleeing from orcs","roll":78,"Level":"1-4"},
    {"Encounter":"3d4 refugees (commoners) fleeing from orcs","roll":79,"Level":"1-4"},
    {"Encounter":"3d4 refugees (commoners) fleeing from orcs","roll":80,"Level":"1-4"},
    {"Encounter":"1d3 veterans","roll":81,"Level":"1-4"},
    {"Encounter":"1d4 orogs","roll":82,"Level":"1-4"},
    {"Encounter":"2 brown bears","roll":83,"Level":"1-4"},
    {"Encounter":"1 orc Eye of Gruumsh and 2d8 orcs","roll":84,"Level":"1-4"},
    {"Encounter":"1d3 winter wolves","roll":85,"Level":"1-4"},
    {"Encounter":"1d4 yetis","roll":86,"Level":"1-4"},
    {"Encounter":"1d4 yetis","roll":87,"Level":"1-4"},
    {"Encounter":"1 half-ogre","roll":88,"Level":"1-4"},
    {"Encounter":"1d3 manticores","roll":89,"Level":"1-4"},
    {"Encounter":"1 bandit captain with 2d6 bandits","roll":90,"Level":"1-4"},
    {"Encounter":"1 revenant","roll":91,"Level":"1-4"},
    {"Encounter":"1 troll","roll":92,"Level":"1-4"},
    {"Encounter":"1 troll","roll":93,"Level":"1-4"},
    {"Encounter":"1 werebear","roll":94,"Level":"1-4"},
    {"Encounter":"1 werebear","roll":95,"Level":"1-4"},
    {"Encounter":"1 young remorhaz","roll":96,"Level":"1-4"},
    {"Encounter":"1 young remorhaz","roll":97,"Level":"1-4"},
    {"Encounter":"1 mammoth","roll":98,"Level":"1-4"},
    {"Encounter":"1 young white dragon","roll":99,"Level":"1-4"},
    {"Encounter":"1 frost giant","roll":100,"Level":"1-4"},
    {"Encounter":"1 ancient white dragon","roll":0,"Level":"11-16"},
    {"Encounter":"1d6 revenants","roll":2,"Level":"11-16"},
    {"Encounter":"1d6 revenants","roll":3,"Level":"11-16"},
    {"Encounter":"1d6 revenants","roll":4,"Level":"11-16"},
    {"Encounter":"1d4+1 werebears","roll":5,"Level":"11-16"},
    {"Encounter":"1d4+1 werebears","roll":6,"Level":"11-16"},
    {"Encounter":"1d4+1 werebears","roll":7,"Level":"11-16"},
    {"Encounter":"1d4+1 werebears","roll":8,"Level":"11-16"},
    {"Encounter":"1d4+1 werebears","roll":9,"Level":"11-16"},
    {"Encounter":"1d4+1 werebears","roll":10,"Level":"11-16"},
    {"Encounter":"1d3 young white dragons","roll":11,"Level":"11-16"},
    {"Encounter":"1d3 young white dragons","roll":12,"Level":"11-16"},
    {"Encounter":"1d3 young white dragons","roll":13,"Level":"11-16"},
    {"Encounter":"1d3 young white dragons","roll":14,"Level":"11-16"},
    {"Encounter":"1d3 young white dragons","roll":15,"Level":"11-16"},
    {"Encounter":"1d3 young white dragons","roll":16,"Level":"11-16"},
    {"Encounter":"1d3 young white dragons","roll":17,"Level":"11-16"},
    {"Encounter":"1d3 young white dragons","roll":18,"Level":"11-16"},
    {"Encounter":"1d3 young white dragons","roll":19,"Level":"11-16"},
    {"Encounter":"1d3 young white dragons","roll":20,"Level":"11-16"},
    {"Encounter":"A blizzard that reduces visibility to 5 feet for 1d6 hours","roll":21,"Level":"11-16"},
    {"Encounter":"A blizzard that reduces visibility to 5 feet for 1d6 hours","roll":22,"Level":"11-16"},
    {"Encounter":"A blizzard that reduces visibility to 5 feet for 1d6 hours","roll":23,"Level":"11-16"},
    {"Encounter":"A blizzard that reduces visibility to 5 feet for 1d6 hours","roll":24,"Level":"11-16"},
    {"Encounter":"A blizzard that reduces visibility to 5 feet for 1d6 hours","roll":25,"Level":"11-16"},
    {"Encounter":"1 roc","roll":26,"Level":"11-16"},
    {"Encounter":"1 roc","roll":27,"Level":"11-16"},
    {"Encounter":"1 roc","roll":28,"Level":"11-16"},
    {"Encounter":"1 roc","roll":29,"Level":"11-16"},
    {"Encounter":"1 roc","roll":30,"Level":"11-16"},
    {"Encounter":"1 roc","roll":31,"Level":"11-16"},
    {"Encounter":"1 roc","roll":32,"Level":"11-16"},
    {"Encounter":"1 roc","roll":33,"Level":"11-16"},
    {"Encounter":"1 roc","roll":34,"Level":"11-16"},
    {"Encounter":"1 roc","roll":35,"Level":"11-16"},
    {"Encounter":"A herd of 3d20+60 caribou (deer) moving through the snow","roll":36,"Level":"11-16"},
    {"Encounter":"A herd of 3d20+60 caribou (deer) moving through the snow","roll":37,"Level":"11-16"},
    {"Encounter":"A herd of 3d20+60 caribou (deer) moving through the snow","roll":38,"Level":"11-16"},
    {"Encounter":"A herd of 3d20+60 caribou (deer) moving through the snow","roll":39,"Level":"11-16"},
    {"Encounter":"A herd of 3d20+60 caribou (deer) moving through the snow","roll":40,"Level":"11-16"},
    {"Encounter":"1d4 mammoths","roll":41,"Level":"11-16"},
    {"Encounter":"1d4 mammoths","roll":42,"Level":"11-16"},
    {"Encounter":"1d4 mammoths","roll":43,"Level":"11-16"},
    {"Encounter":"1d4 mammoths","roll":44,"Level":"11-16"},
    {"Encounter":"1d4 mammoths","roll":45,"Level":"11-16"},
    {"Encounter":"1d4 mammoths","roll":46,"Level":"11-16"},
    {"Encounter":"1d4 mammoths","roll":47,"Level":"11-16"},
    {"Encounter":"1d4 mammoths","roll":48,"Level":"11-16"},
    {"Encounter":"1d4 mammoths","roll":49,"Level":"11-16"},
    {"Encounter":"1d4 mammoths","roll":50,"Level":"11-16"},
    {"Encounter":"1d8+1 trolls","roll":51,"Level":"11-16"},
    {"Encounter":"1d8+1 trolls","roll":52,"Level":"11-16"},
    {"Encounter":"1d8+1 trolls","roll":53,"Level":"11-16"},
    {"Encounter":"1d8+1 trolls","roll":54,"Level":"11-16"},
    {"Encounter":"1d8+1 trolls","roll":55,"Level":"11-16"},
    {"Encounter":"1d8+1 trolls","roll":56,"Level":"11-16"},
    {"Encounter":"1d8+1 trolls","roll":57,"Level":"11-16"},
    {"Encounter":"1d8+1 trolls","roll":58,"Level":"11-16"},
    {"Encounter":"1d8+1 trolls","roll":59,"Level":"11-16"},
    {"Encounter":"1d8+1 trolls","roll":60,"Level":"11-16"},
    {"Encounter":"A mile-wide frozen lake in which preserved corpses of strange creatures can be seen","roll":61,"Level":"11-16"},
    {"Encounter":"A mile-wide frozen lake in which preserved corpses of strange creatures can be seen","roll":62,"Level":"11-16"},
    {"Encounter":"A mile-wide frozen lake in which preserved corpses of strange creatures can be seen","roll":63,"Level":"11-16"},
    {"Encounter":"A mile-wide frozen lake in which preserved corpses of strange creatures can be seen","roll":64,"Level":"11-16"},
    {"Encounter":"A mile-wide frozen lake in which preserved corpses of strange creatures can be seen","roll":65,"Level":"11-16"},
    {"Encounter":"2d4 young remorhazes","roll":66,"Level":"11-16"},
    {"Encounter":"2d4 young remorhazes","roll":67,"Level":"11-16"},
    {"Encounter":"2d4 young remorhazes","roll":68,"Level":"11-16"},
    {"Encounter":"2d4 young remorhazes","roll":69,"Level":"11-16"},
    {"Encounter":"2d4 young remorhazes","roll":70,"Level":"11-16"},
    {"Encounter":"2d4 young remorhazes","roll":71,"Level":"11-16"},
    {"Encounter":"2d4 young remorhazes","roll":72,"Level":"11-16"},
    {"Encounter":"2d4 young remorhazes","roll":73,"Level":"11-16"},
    {"Encounter":"2d4 young remorhazes","roll":74,"Level":"11-16"},
    {"Encounter":"2d4 young remorhazes","roll":75,"Level":"11-16"},
    {"Encounter":"A crumbling ice castle littered with the frozen bodies of blue-skinned humanoids","roll":76,"Level":"11-16"},
    {"Encounter":"A crumbling ice castle littered with the frozen bodies of blue-skinned humanoids","roll":77,"Level":"11-16"},
    {"Encounter":"A crumbling ice castle littered with the frozen bodies of blue-skinned humanoids","roll":78,"Level":"11-16"},
    {"Encounter":"A crumbling ice castle littered with the frozen bodies of blue-skinned humanoids","roll":79,"Level":"11-16"},
    {"Encounter":"A crumbling ice castle littered with the frozen bodies of blue-skinned humanoids","roll":80,"Level":"11-16"},
    {"Encounter":"1 adult white dragon","roll":81,"Level":"11-16"},
    {"Encounter":"1 adult white dragon","roll":82,"Level":"11-16"},
    {"Encounter":"1 adult white dragon","roll":83,"Level":"11-16"},
    {"Encounter":"1 adult white dragon","roll":84,"Level":"11-16"},
    {"Encounter":"1 adult white dragon","roll":85,"Level":"11-16"},
    {"Encounter":"1 adult white dragon","roll":86,"Level":"11-16"},
    {"Encounter":"1 adult white dragon","roll":87,"Level":"11-16"},
    {"Encounter":"1 adult white dragon","roll":88,"Level":"11-16"},
    {"Encounter":"1 adult white dragon","roll":89,"Level":"11-16"},
    {"Encounter":"1 adult white dragon","roll":90,"Level":"11-16"},
    {"Encounter":"1d8+1 frost giants","roll":91,"Level":"11-16"},
    {"Encounter":"1d8+1 frost giants","roll":92,"Level":"11-16"},
    {"Encounter":"1d8+1 frost giants","roll":93,"Level":"11-16"},
    {"Encounter":"1d8+1 frost giants","roll":94,"Level":"11-16"},
    {"Encounter":"1d8+1 frost giants","roll":95,"Level":"11-16"},
    {"Encounter":"1d8+1 frost giants","roll":96,"Level":"11-16"},
    {"Encounter":"1d4 young remorhazes","roll":97,"Level":"11-16"},
    {"Encounter":"1d4 young remorhazes","roll":98,"Level":"11-16"},
    {"Encounter":"1d4 young remorhazes","roll":99,"Level":"11-16"},
    {"Encounter":"1 ancient white dragon","roll":100,"Level":"11-16"},
    {"Encounter":"2d10 revenants","roll":1,"Level":"17-20"},
    {"Encounter":"2d10 revenants","roll":2,"Level":"17-20"},
    {"Encounter":"2d8 trolls","roll":3,"Level":"17-20"},
    {"Encounter":"2d8 trolls","roll":4,"Level":"17-20"},
    {"Encounter":"2d10 werebears","roll":5,"Level":"17-20"},
    {"Encounter":"2d10 werebears","roll":6,"Level":"17-20"},
    {"Encounter":"1 frost giant","roll":7,"Level":"17-20"},
    {"Encounter":"1 frost giant","roll":8,"Level":"17-20"},
    {"Encounter":"2d4 young remorhazes","roll":9,"Level":"17-20"},
    {"Encounter":"2d4 young remorhazes","roll":10,"Level":"17-20"},
    {"Encounter":"1d4 frost giants","roll":11,"Level":"17-20"},
    {"Encounter":"1d4 frost giants","roll":12,"Level":"17-20"},
    {"Encounter":"1d4 frost giants","roll":13,"Level":"17-20"},
    {"Encounter":"1d4 frost giants","roll":14,"Level":"17-20"},
    {"Encounter":"1d4 frost giants","roll":15,"Level":"17-20"},
    {"Encounter":"1d4 frost giants","roll":16,"Level":"17-20"},
    {"Encounter":"1d4 frost giants","roll":17,"Level":"17-20"},
    {"Encounter":"1d4 frost giants","roll":18,"Level":"17-20"},
    {"Encounter":"1d4 frost giants","roll":19,"Level":"17-20"},
    {"Encounter":"1d4 frost giants","roll":20,"Level":"17-20"},
    {"Encounter":"A Circular patch of black ice on the ground. The air temperature around the patch is warmer than in the surrounding area, and characters who inspect the ice find bits of machinery frozen within.","roll":21,"Level":"17-20"},
    {"Encounter":"A Circular patch of black ice on the ground. The air temperature around the patch is warmer than in the surrounding area, and characters who inspect the ice find bits of machinery frozen within.","roll":22,"Level":"17-20"},
    {"Encounter":"A Circular patch of black ice on the ground. The air temperature around the patch is warmer than in the surrounding area, and characters who inspect the ice find bits of machinery frozen within.","roll":23,"Level":"17-20"},
    {"Encounter":"A Circular patch of black ice on the ground. The air temperature around the patch is warmer than in the surrounding area, and characters who inspect the ice find bits of machinery frozen within.","roll":24,"Level":"17-20"},
    {"Encounter":"A Circular patch of black ice on the ground. The air temperature around the patch is warmer than in the surrounding area, and characters who inspect the ice find bits of machinery frozen within.","roll":25,"Level":"17-20"},
    {"Encounter":"1 ancient white dragon","roll":26,"Level":"17-20"},
    {"Encounter":"1 ancient white dragon","roll":27,"Level":"17-20"},
    {"Encounter":"1 ancient white dragon","roll":28,"Level":"17-20"},
    {"Encounter":"1 ancient white dragon","roll":29,"Level":"17-20"},
    {"Encounter":"1 ancient white dragon","roll":30,"Level":"17-20"},
    {"Encounter":"1 ancient white dragon","roll":31,"Level":"17-20"},
    {"Encounter":"1 ancient white dragon","roll":32,"Level":"17-20"},
    {"Encounter":"1 ancient white dragon","roll":33,"Level":"17-20"},
    {"Encounter":"1 ancient white dragon","roll":34,"Level":"17-20"},
    {"Encounter":"1 ancient white dragon","roll":35,"Level":"17-20"},
    {"Encounter":"An adventurer frozen 6 feet under the ice; 50% chance the corpse has a rare magic item of the DM's choice","roll":36,"Level":"17-20"},
    {"Encounter":"An adventurer frozen 6 feet under the ice; 50% chance the corpse has a rare magic item of the DM's choice","roll":37,"Level":"17-20"},
    {"Encounter":"An adventurer frozen 6 feet under the ice; 50% chance the corpse has a rare magic item of the DM's choice","roll":38,"Level":"17-20"},
    {"Encounter":"An adventurer frozen 6 feet under the ice; 50% chance the corpse has a rare magic item of the DM's choice","roll":39,"Level":"17-20"},
    {"Encounter":"An adventurer frozen 6 feet under the ice; 50% chance the corpse has a rare magic item of the DM's choice","roll":40,"Level":"17-20"},
    {"Encounter":"1d3 abominable yetis","roll":41,"Level":"17-20"},
    {"Encounter":"1d3 abominable yetis","roll":42,"Level":"17-20"},
    {"Encounter":"1d3 abominable yetis","roll":43,"Level":"17-20"},
    {"Encounter":"1d3 abominable yetis","roll":44,"Level":"17-20"},
    {"Encounter":"1d3 abominable yetis","roll":45,"Level":"17-20"},
    {"Encounter":"1d3 abominable yetis","roll":46,"Level":"17-20"},
    {"Encounter":"1d3 abominable yetis","roll":47,"Level":"17-20"},
    {"Encounter":"1d3 abominable yetis","roll":48,"Level":"17-20"},
    {"Encounter":"1d3 abominable yetis","roll":49,"Level":"17-20"},
    {"Encounter":"1d3 abominable yetis","roll":50,"Level":"17-20"},
    {"Encounter":"1d4 remorhazes","roll":51,"Level":"17-20"},
    {"Encounter":"1d4 remorhazes","roll":52,"Level":"17-20"},
    {"Encounter":"1d4 remorhazes","roll":53,"Level":"17-20"},
    {"Encounter":"1d4 remorhazes","roll":54,"Level":"17-20"},
    {"Encounter":"1d4 remorhazes","roll":55,"Level":"17-20"},
    {"Encounter":"1d4 remorhazes","roll":56,"Level":"17-20"},
    {"Encounter":"1d4 remorhazes","roll":57,"Level":"17-20"},
    {"Encounter":"1d4 remorhazes","roll":58,"Level":"17-20"},
    {"Encounter":"1d4 remorhazes","roll":59,"Level":"17-20"},
    {"Encounter":"1d4 remorhazes","roll":60,"Level":"17-20"},
    {"Encounter":"A 500-foot-high wall of ice that is 300 feet thick and spread across 1d4 miles","roll":61,"Level":"17-20"},
    {"Encounter":"A 500-foot-high wall of ice that is 300 feet thick and spread across 1d4 miles","roll":62,"Level":"17-20"},
    {"Encounter":"A 500-foot-high wall of ice that is 300 feet thick and spread across 1d4 miles","roll":63,"Level":"17-20"},
    {"Encounter":"A 500-foot-high wall of ice that is 300 feet thick and spread across 1d4 miles","roll":64,"Level":"17-20"},
    {"Encounter":"A 500-foot-high wall of ice that is 300 feet thick and spread across 1d4 miles","roll":65,"Level":"17-20"},
    {"Encounter":"1d4 rocs","roll":66,"Level":"17-20"},
    {"Encounter":"1d4 rocs","roll":67,"Level":"17-20"},
    {"Encounter":"1d4 rocs","roll":68,"Level":"17-20"},
    {"Encounter":"1d4 rocs","roll":69,"Level":"17-20"},
    {"Encounter":"1d4 rocs","roll":70,"Level":"17-20"},
    {"Encounter":"1d4 rocs","roll":71,"Level":"17-20"},
    {"Encounter":"1d4 rocs","roll":72,"Level":"17-20"},
    {"Encounter":"1d4 rocs","roll":73,"Level":"17-20"},
    {"Encounter":"1d4 rocs","roll":74,"Level":"17-20"},
    {"Encounter":"1d4 rocs","roll":75,"Level":"17-20"},
    {"Encounter":"The likeness of a stern woman with long, flowing hair, carved into the side of a mountain","roll":76,"Level":"17-20"},
    {"Encounter":"The likeness of a stern woman with long, flowing hair, carved into the side of a mountain","roll":77,"Level":"17-20"},
    {"Encounter":"The likeness of a stern woman with long, flowing hair, carved into the side of a mountain","roll":78,"Level":"17-20"},
    {"Encounter":"The likeness of a stern woman with long, flowing hair, carved into the side of a mountain","roll":79,"Level":"17-20"},
    {"Encounter":"The likeness of a stern woman with long, flowing hair, carved into the side of a mountain","roll":80,"Level":"17-20"},
    {"Encounter":"1d10 frost giants with 2d4 polar bears","roll":81,"Level":"17-20"},
    {"Encounter":"1d10 frost giants with 2d4 polar bears","roll":82,"Level":"17-20"},
    {"Encounter":"1d10 frost giants with 2d4 polar bears","roll":83,"Level":"17-20"},
    {"Encounter":"1d10 frost giants with 2d4 polar bears","roll":84,"Level":"17-20"},
    {"Encounter":"1d10 frost giants with 2d4 polar bears","roll":85,"Level":"17-20"},
    {"Encounter":"1d10 frost giants with 2d4 polar bears","roll":86,"Level":"17-20"},
    {"Encounter":"1d10 frost giants with 2d4 polar bears","roll":87,"Level":"17-20"},
    {"Encounter":"1d10 frost giants with 2d4 polar bears","roll":88,"Level":"17-20"},
    {"Encounter":"1d10 frost giants with 2d4 polar bears","roll":89,"Level":"17-20"},
    {"Encounter":"1d10 frost giants with 2d4 polar bears","roll":90,"Level":"17-20"},
    {"Encounter":"1d3 adult white dragons","roll":91,"Level":"17-20"},
    {"Encounter":"1d3 adult white dragons","roll":92,"Level":"17-20"},
    {"Encounter":"1d3 adult white dragons","roll":93,"Level":"17-20"},
    {"Encounter":"1d3 adult white dragons","roll":94,"Level":"17-20"},
    {"Encounter":"1d3 adult white dragons","roll":95,"Level":"17-20"},
    {"Encounter":"1d3 adult white dragons","roll":96,"Level":"17-20"},
    {"Encounter":"2d4 abominable yetis","roll":97,"Level":"17-20"},
    {"Encounter":"2d4 abominable yetis","roll":98,"Level":"17-20"},
    {"Encounter":"2d4 abominable yetis","roll":99,"Level":"17-20"},
    {"Encounter":"1 ancient white dragon with 1d3 young white dragons","roll":100,"Level":"17-20"},
    {"Encounter":"1 abominable yeti","roll":1,"Level":"5-10"},
    {"Encounter":"2 saber-toothed tigers","roll":1,"Level":"5-10"},
    {"Encounter":"2 saber-toothed tigers","roll":2,"Level":"5-10"},
    {"Encounter":"2 saber-toothed tigers","roll":3,"Level":"5-10"},
    {"Encounter":"2 saber-toothed tigers","roll":4,"Level":"5-10"},
    {"Encounter":"2 saber-toothed tigers","roll":5,"Level":"5-10"},
    {"Encounter":"1d4 half-ogres","roll":6,"Level":"5-10"},
    {"Encounter":"1d4 half-ogres","roll":7,"Level":"5-10"},
    {"Encounter":"1d3+1 brown bears","roll":8,"Level":"5-10"},
    {"Encounter":"1d3+1 brown bears","roll":9,"Level":"5-10"},
    {"Encounter":"1d3+1 brown bears","roll":10,"Level":"5-10"},
    {"Encounter":"1d3 polar bears","roll":11,"Level":"5-10"},
    {"Encounter":"1d3 polar bears","roll":12,"Level":"5-10"},
    {"Encounter":"1d3 polar bears","roll":13,"Level":"5-10"},
    {"Encounter":"1d3 polar bears","roll":14,"Level":"5-10"},
    {"Encounter":"1d3 polar bears","roll":15,"Level":"5-10"},
    {"Encounter":"2d4 berserkers","roll":16,"Level":"5-10"},
    {"Encounter":"2d4 berserkers","roll":17,"Level":"5-10"},
    {"Encounter":"2d4 berserkers","roll":18,"Level":"5-10"},
    {"Encounter":"2d4 berserkers","roll":19,"Level":"5-10"},
    {"Encounter":"2d4 berserkers","roll":20,"Level":"5-10"},
    {"Encounter":"A half-orc druid tending to an injured polar bear. If the characters assist the druid, she gives them a vial of antitoxin.","roll":21,"Level":"5-10"},
    {"Encounter":"A half-orc druid tending to an injured polar bear. If the characters assist the druid, she gives them a vial of antitoxin.","roll":22,"Level":"5-10"},
    {"Encounter":"A half-orc druid tending to an injured polar bear. If the characters assist the druid, she gives them a vial of antitoxin.","roll":23,"Level":"5-10"},
    {"Encounter":"A half-orc druid tending to an injured polar bear. If the characters assist the druid, she gives them a vial of antitoxin.","roll":24,"Level":"5-10"},
    {"Encounter":"A half-orc druid tending to an injured polar bear. If the characters assist the druid, she gives them a vial of antitoxin.","roll":25,"Level":"5-10"},
    {"Encounter":"2d8 scouts","roll":26,"Level":"5-10"},
    {"Encounter":"2d8 scouts","roll":27,"Level":"5-10"},
    {"Encounter":"2d8 scouts","roll":28,"Level":"5-10"},
    {"Encounter":"2d8 scouts","roll":29,"Level":"5-10"},
    {"Encounter":"2d8 scouts","roll":30,"Level":"5-10"},
    {"Encounter":"2d4 ice mephits","roll":31,"Level":"5-10"},
    {"Encounter":"2d4 ice mephits","roll":32,"Level":"5-10"},
    {"Encounter":"2d4 ice mephits","roll":33,"Level":"5-10"},
    {"Encounter":"2d4 ice mephits","roll":34,"Level":"5-10"},
    {"Encounter":"2d4 ice mephits","roll":35,"Level":"5-10"},
    {"Encounter":"2d6+1 zombies aboard a galleon trapped in the ice. Searching the ship yields 2d20 days of rations.","roll":36,"Level":"5-10"},
    {"Encounter":"2d6+1 zombies aboard a galleon trapped in the ice. Searching the ship yields 2d20 days of rations.","roll":37,"Level":"5-10"},
    {"Encounter":"2d6+1 zombies aboard a galleon trapped in the ice. Searching the ship yields 2d20 days of rations.","roll":38,"Level":"5-10"},
    {"Encounter":"2d6+1 zombies aboard a galleon trapped in the ice. Searching the ship yields 2d20 days of rations.","roll":39,"Level":"5-10"},
    {"Encounter":"2d6+1 zombies aboard a galleon trapped in the ice. Searching the ship yields 2d20 days of rations.","roll":40,"Level":"5-10"},
    {"Encounter":"1 manticore","roll":41,"Level":"5-10"},
    {"Encounter":"1 manticore","roll":42,"Level":"5-10"},
    {"Encounter":"1 manticore","roll":43,"Level":"5-10"},
    {"Encounter":"1 manticore","roll":44,"Level":"5-10"},
    {"Encounter":"1 manticore","roll":45,"Level":"5-10"},
    {"Encounter":"2d6+3 orcs","roll":46,"Level":"5-10"},
    {"Encounter":"2d6+3 orcs","roll":47,"Level":"5-10"},
    {"Encounter":"2d6+3 orcs","roll":48,"Level":"5-10"},
    {"Encounter":"2d6+3 orcs","roll":49,"Level":"5-10"},
    {"Encounter":"2d6+3 orcs","roll":50,"Level":"5-10"},
    {"Encounter":"1d6+2 ogres","roll":51,"Level":"5-10"},
    {"Encounter":"1d6+2 ogres","roll":52,"Level":"5-10"},
    {"Encounter":"1d6+2 ogres","roll":53,"Level":"5-10"},
    {"Encounter":"2d4 griffons","roll":54,"Level":"5-10"},
    {"Encounter":"2d4 griffons","roll":55,"Level":"5-10"},
    {"Encounter":"1d4 veterans","roll":56,"Level":"5-10"},
    {"Encounter":"1d4 veterans","roll":57,"Level":"5-10"},
    {"Encounter":"1 bandit captain with 1 druid, 1d3 berserkers, and 2d10+5 bandits","roll":58,"Level":"5-10"},
    {"Encounter":"1 bandit captain with 1 druid, 1d3 berserkers, and 2d10+5 bandits","roll":59,"Level":"5-10"},
    {"Encounter":"1 bandit captain with 1 druid, 1d3 berserkers, and 2d10+5 bandits","roll":60,"Level":"5-10"},
    {"Encounter":"1d4 hours of extreme cold (see chapter 5 of the Dungeon Master's Guide)","roll":61,"Level":"5-10"},
    {"Encounter":"1d4 hours of extreme cold (see chapter 5 of the Dungeon Master's Guide)","roll":62,"Level":"5-10"},
    {"Encounter":"1d4 hours of extreme cold (see chapter 5 of the Dungeon Master's Guide)","roll":63,"Level":"5-10"},
    {"Encounter":"1d4 hours of extreme cold (see chapter 5 of the Dungeon Master's Guide)","roll":64,"Level":"5-10"},
    {"Encounter":"1d4 hours of extreme cold (see chapter 5 of the Dungeon Master's Guide)","roll":65,"Level":"5-10"},
    {"Encounter":"1 young remorhaz","roll":66,"Level":"5-10"},
    {"Encounter":"1 young remorhaz","roll":67,"Level":"5-10"},
    {"Encounter":"1 young remorhaz","roll":68,"Level":"5-10"},
    {"Encounter":"1 orc Eye of Gruumsh with 1d6 orogs and 2d8+6 orcs","roll":69,"Level":"5-10"},
    {"Encounter":"1 orc Eye of Gruumsh with 1d6 orogs and 2d8+6 orcs","roll":70,"Level":"5-10"},
    {"Encounter":"1 orc Eye of Gruumsh with 1d6 orogs and 2d8+6 orcs","roll":71,"Level":"5-10"},
    {"Encounter":"1 orc Eye of Gruumsh with 1d6 orogs and 2d8+6 orcs","roll":72,"Level":"5-10"},
    {"Encounter":"1 revenant","roll":73,"Level":"5-10"},
    {"Encounter":"1 revenant","roll":74,"Level":"5-10"},
    {"Encounter":"1 revenant","roll":75,"Level":"5-10"},
    {"Encounter":"A howl that echoes over the land for 1d3 minutes","roll":76,"Level":"5-10"},
    {"Encounter":"A howl that echoes over the land for 1d3 minutes","roll":77,"Level":"5-10"},
    {"Encounter":"A howl that echoes over the land for 1d3 minutes","roll":78,"Level":"5-10"},
    {"Encounter":"A howl that echoes over the land for 1d3 minutes","roll":79,"Level":"5-10"},
    {"Encounter":"A howl that echoes over the land for 1d3 minutes","roll":80,"Level":"5-10"},
    {"Encounter":"1d3 mammoths","roll":81,"Level":"5-10"},
    {"Encounter":"1d3 mammoths","roll":82,"Level":"5-10"},
    {"Encounter":"1 young white dragon","roll":83,"Level":"5-10"},
    {"Encounter":"1 young white dragon","roll":84,"Level":"5-10"},
    {"Encounter":"2d4 winter wolves","roll":85,"Level":"5-10"},
    {"Encounter":"2d4 winter wolves","roll":86,"Level":"5-10"},
    {"Encounter":"1d6+2 yetis","roll":87,"Level":"5-10"},
    {"Encounter":"1d6+2 yetis","roll":88,"Level":"5-10"},
    {"Encounter":"1d2 frost giants","roll":89,"Level":"5-10"},
    {"Encounter":"1d2 frost giants","roll":90,"Level":"5-10"},
    {"Encounter":"1d3 werebears","roll":91,"Level":"5-10"},
    {"Encounter":"1d3 werebears","roll":92,"Level":"5-10"},
    {"Encounter":"1d4 trolls","roll":93,"Level":"5-10"},
    {"Encounter":"1d4 trolls","roll":94,"Level":"5-10"},
    {"Encounter":"1 abominable yeti","roll":95,"Level":"5-10"},
    {"Encounter":"1 abominable yeti","roll":96,"Level":"5-10"},
    {"Encounter":"1 remorhaz","roll":97,"Level":"5-10"},
    {"Encounter":"1 remorhaz","roll":98,"Level":"5-10"},
    {"Encounter":"1 roc","roll":99,"Level":"5-10"},
    {"Encounter":"2d4 young remorhazes","roll":100,"Level":"5-10"}
]
let coastal = [
    {"Encounter":"1 pseudodragon","roll":1,"Level":"1-4"},
    {"Encounter":"2d8 crabs","roll":2,"Level":"1-4"},
    {"Encounter":"2d8 crabs","roll":3,"Level":"1-4"},
    {"Encounter":"2d8 crabs","roll":4,"Level":"1-4"},
    {"Encounter":"2d8 crabs","roll":5,"Level":"1-4"},
    {"Encounter":"2d6 fishers (commoners)","roll":6,"Level":"1-4"},
    {"Encounter":"2d6 fishers (commoners)","roll":7,"Level":"1-4"},
    {"Encounter":"2d6 fishers (commoners)","roll":8,"Level":"1-4"},
    {"Encounter":"2d6 fishers (commoners)","roll":9,"Level":"1-4"},
    {"Encounter":"2d6 fishers (commoners)","roll":10,"Level":"1-4"},
    {"Encounter":"1d3 poisonous snakes","roll":11,"Level":"1-4"},
    {"Encounter":"1d6 guards protecting a standard noble","roll":12,"Level":"1-4"},
    {"Encounter":"1d6 guards protecting a standard noble","roll":13,"Level":"1-4"},
    {"Encounter":"2d4 scouts","roll":14,"Level":"1-4"},
    {"Encounter":"2d4 scouts","roll":15,"Level":"1-4"},
    {"Encounter":"2d10 merfolk","roll":16,"Level":"1-4"},
    {"Encounter":"2d10 merfolk","roll":17,"Level":"1-4"},
    {"Encounter":"2d10 merfolk","roll":18,"Level":"1-4"},
    {"Encounter":"1d6+2 sahuagin","roll":19,"Level":"1-4"},
    {"Encounter":"1d6+2 sahuagin","roll":20,"Level":"1-4"},
    {"Encounter":"1d4 ghouls feeding on corpses aboard the wreckage of a merchant ship. A search uncovers 2d6 bolts of ruined silk, a 50-foot length of rope. and a barrel of salted herring.","roll":21,"Level":"1-4"},
    {"Encounter":"1d4 ghouls feeding on corpses aboard the wreckage of a merchant ship. A search uncovers 2d6 bolts of ruined silk, a 50-foot length of rope. and a barrel of salted herring.","roll":22,"Level":"1-4"},
    {"Encounter":"1d4 ghouls feeding on corpses aboard the wreckage of a merchant ship. A search uncovers 2d6 bolts of ruined silk, a 50-foot length of rope. and a barrel of salted herring.","roll":23,"Level":"1-4"},
    {"Encounter":"1d4 ghouls feeding on corpses aboard the wreckage of a merchant ship. A search uncovers 2d6 bolts of ruined silk, a 50-foot length of rope. and a barrel of salted herring.","roll":24,"Level":"1-4"},
    {"Encounter":"1d4 ghouls feeding on corpses aboard the wreckage of a merchant ship. A search uncovers 2d6 bolts of ruined silk, a 50-foot length of rope. and a barrel of salted herring.","roll":25,"Level":"1-4"},
    {"Encounter":"1d4 winged kobolds with 1d6+1 kobolds","roll":26,"Level":"1-4"},
    {"Encounter":"1d4 winged kobolds with 1d6+1 kobolds","roll":27,"Level":"1-4"},
    {"Encounter":"2d6 tribal warriors","roll":28,"Level":"1-4"},
    {"Encounter":"2d6 tribal warriors","roll":29,"Level":"1-4"},
    {"Encounter":"3d4 kobolds","roll":30,"Level":"1-4"},
    {"Encounter":"3d4 kobolds","roll":31,"Level":"1-4"},
    {"Encounter":"2d4+5 blood hawks","roll":32,"Level":"1-4"},
    {"Encounter":"2d4+5 blood hawks","roll":33,"Level":"1-4"},
    {"Encounter":"1d8+1 pteranodons","roll":34,"Level":"1-4"},
    {"Encounter":"1d8+1 pteranodons","roll":35,"Level":"1-4"},
    {"Encounter":"A few dozen baby turtles struggling to make their way to the sea","roll":36,"Level":"1-4"},
    {"Encounter":"A few dozen baby turtles struggling to make their way to the sea","roll":37,"Level":"1-4"},
    {"Encounter":"A few dozen baby turtles struggling to make their way to the sea","roll":38,"Level":"1-4"},
    {"Encounter":"A few dozen baby turtles struggling to make their way to the sea","roll":39,"Level":"1-4"},
    {"Encounter":"A few dozen baby turtles struggling to make their way to the sea","roll":40,"Level":"1-4"},
    {"Encounter":"1d6+2 giant lizards","roll":41,"Level":"1-4"},
    {"Encounter":"1d6+2 giant lizards","roll":42,"Level":"1-4"},
    {"Encounter":"1d6+4 giant crabs","roll":43,"Level":"1-4"},
    {"Encounter":"1d6+4 giant crabs","roll":44,"Level":"1-4"},
    {"Encounter":"2d4 stirges","roll":45,"Level":"1-4"},
    {"Encounter":"2d4 stirges","roll":46,"Level":"1-4"},
    {"Encounter":"2d6+3 bandits","roll":47,"Level":"1-4"},
    {"Encounter":"2d6+3 bandits","roll":48,"Level":"1-4"},
    {"Encounter":"2d4 sahuagin","roll":49,"Level":"1-4"},
    {"Encounter":"2d4 sahuagin","roll":50,"Level":"1-4"},
    {"Encounter":"2d4 sahuagin","roll":51,"Level":"1-4"},
    {"Encounter":"2d4 sahuagin","roll":52,"Level":"1-4"},
    {"Encounter":"2d4 sahuagin","roll":53,"Level":"1-4"},
    {"Encounter":"1d6+2 scouts","roll":54,"Level":"1-4"},
    {"Encounter":"1d6+2 scouts","roll":55,"Level":"1-4"},
    {"Encounter":"1 sea hag","roll":56,"Level":"1-4"},
    {"Encounter":"1 sea hag","roll":57,"Level":"1-4"},
    {"Encounter":"1 sea hag","roll":58,"Level":"1-4"},
    {"Encounter":"1 sea hag","roll":59,"Level":"1-4"},
    {"Encounter":"1 sea hag","roll":60,"Level":"1-4"},
    {"Encounter":"A momentary formation in the waves that looks like an enormous humanoid face","roll":61,"Level":"1-4"},
    {"Encounter":"A momentary formation in the waves that looks like an enormous humanoid face","roll":62,"Level":"1-4"},
    {"Encounter":"A momentary formation in the waves that looks like an enormous humanoid face","roll":63,"Level":"1-4"},
    {"Encounter":"A momentary formation in the waves that looks like an enormous humanoid face","roll":64,"Level":"1-4"},
    {"Encounter":"A momentary formation in the waves that looks like an enormous humanoid face","roll":65,"Level":"1-4"},
    {"Encounter":"1 druid","roll":66,"Level":"1-4"},
    {"Encounter":"1 druid","roll":67,"Level":"1-4"},
    {"Encounter":"1 druid","roll":68,"Level":"1-4"},
    {"Encounter":"1 druid","roll":69,"Level":"1-4"},
    {"Encounter":"1 druid","roll":70,"Level":"1-4"},
    {"Encounter":"1d4 harpies","roll":71,"Level":"1-4"},
    {"Encounter":"1d4 harpies","roll":72,"Level":"1-4"},
    {"Encounter":"1d4 harpies","roll":73,"Level":"1-4"},
    {"Encounter":"1d4 harpies","roll":74,"Level":"1-4"},
    {"Encounter":"1d4 harpies","roll":75,"Level":"1-4"},
    {"Encounter":"A lone hermit (acolyte) sitting on the beach contemplating the meaning of the multiverse","roll":76,"Level":"1-4"},
    {"Encounter":"A lone hermit (acolyte) sitting on the beach contemplating the meaning of the multiverse","roll":77,"Level":"1-4"},
    {"Encounter":"A lone hermit (acolyte) sitting on the beach contemplating the meaning of the multiverse","roll":78,"Level":"1-4"},
    {"Encounter":"A lone hermit (acolyte) sitting on the beach contemplating the meaning of the multiverse","roll":79,"Level":"1-4"},
    {"Encounter":"A lone hermit (acolyte) sitting on the beach contemplating the meaning of the multiverse","roll":80,"Level":"1-4"},
    {"Encounter":"1d4 berserkers","roll":81,"Level":"1-4"},
    {"Encounter":"1d6 giant eagles","roll":82,"Level":"1-4"},
    {"Encounter":"2d4 giant toads","roll":83,"Level":"1-4"},
    {"Encounter":"1d4 ogres or 1d4 merrow","roll":84,"Level":"1-4"},
    {"Encounter":"3d6 sahuagin","roll":85,"Level":"1-4"},
    {"Encounter":"1d4 veterans","roll":86,"Level":"1-4"},
    {"Encounter":"1d2 plesiosauruses","roll":87,"Level":"1-4"},
    {"Encounter":"1 bandit captain with 2d6 bandits","roll":88,"Level":"1-4"},
    {"Encounter":"1d3 manticores","roll":89,"Level":"1-4"},
    {"Encounter":"1 banshee","roll":90,"Level":"1-4"},
    {"Encounter":"1d4+3 griffons","roll":91,"Level":"1-4"},
    {"Encounter":"1d4+3 griffons","roll":92,"Level":"1-4"},
    {"Encounter":"1 sahuagin priestess with 1d3 merrow and 2d6 sahuagin","roll":93,"Level":"1-4"},
    {"Encounter":"1 sahuagin priestess with 1d3 merrow and 2d6 sahuagin","roll":94,"Level":"1-4"},
    {"Encounter":"1 sahuagin baron","roll":95,"Level":"1-4"},
    {"Encounter":"1 sahuagin baron","roll":96,"Level":"1-4"},
    {"Encounter":"1 water elemental","roll":97,"Level":"1-4"},
    {"Encounter":"1 water elemental","roll":98,"Level":"1-4"},
    {"Encounter":"1 cyclops","roll":99,"Level":"1-4"},
    {"Encounter":"1 young bronze dragon","roll":100,"Level":"1-4"},
    {"Encounter":"1d4 banshees (night only)","roll":1,"Level":"11-16"},
    {"Encounter":"1 cyclops","roll":2,"Level":"11-16"},
    {"Encounter":"1 cyclops","roll":3,"Level":"11-16"},
    {"Encounter":"1 cyclops","roll":4,"Level":"11-16"},
    {"Encounter":"1d6+2 manticores","roll":5,"Level":"11-16"},
    {"Encounter":"1d6+2 manticores","roll":6,"Level":"11-16"},
    {"Encounter":"1d6+2 manticores","roll":7,"Level":"11-16"},
    {"Encounter":"1d6+2 manticores","roll":8,"Level":"11-16"},
    {"Encounter":"1d8+2 veterans","roll":9,"Level":"11-16"},
    {"Encounter":"1d8+2 veterans","roll":10,"Level":"11-16"},
    {"Encounter":"1 young blue dragon","roll":11,"Level":"11-16"},
    {"Encounter":"1 young blue dragon","roll":12,"Level":"11-16"},
    {"Encounter":"1 young blue dragon","roll":13,"Level":"11-16"},
    {"Encounter":"1 young blue dragon","roll":14,"Level":"11-16"},
    {"Encounter":"1 young blue dragon","roll":15,"Level":"11-16"},
    {"Encounter":"1 young blue dragon","roll":16,"Level":"11-16"},
    {"Encounter":"1 young blue dragon","roll":17,"Level":"11-16"},
    {"Encounter":"1 young blue dragon","roll":18,"Level":"11-16"},
    {"Encounter":"1 young blue dragon","roll":19,"Level":"11-16"},
    {"Encounter":"1 young blue dragon","roll":20,"Level":"11-16"},
    {"Encounter":"A nest of 1d6 dragon turtle eggs","roll":21,"Level":"11-16"},
    {"Encounter":"A nest of 1d6 dragon turtle eggs","roll":22,"Level":"11-16"},
    {"Encounter":"A nest of 1d6 dragon turtle eggs","roll":23,"Level":"11-16"},
    {"Encounter":"A nest of 1d6 dragon turtle eggs","roll":24,"Level":"11-16"},
    {"Encounter":"A nest of 1d6 dragon turtle eggs","roll":25,"Level":"11-16"},
    {"Encounter":"1d4 sahuagin barons","roll":26,"Level":"11-16"},
    {"Encounter":"1d4 sahuagin barons","roll":27,"Level":"11-16"},
    {"Encounter":"1d4 sahuagin barons","roll":28,"Level":"11-16"},
    {"Encounter":"1d4 sahuagin barons","roll":29,"Level":"11-16"},
    {"Encounter":"1d4 sahuagin barons","roll":30,"Level":"11-16"},
    {"Encounter":"1d4 sahuagin barons","roll":31,"Level":"11-16"},
    {"Encounter":"1d4 sahuagin barons","roll":32,"Level":"11-16"},
    {"Encounter":"1d4 sahuagin barons","roll":33,"Level":"11-16"},
    {"Encounter":"1d4 sahuagin barons","roll":34,"Level":"11-16"},
    {"Encounter":"1d4 sahuagin barons","roll":35,"Level":"11-16"},
    {"Encounter":"A trident partially buried in the sand","roll":36,"Level":"11-16"},
    {"Encounter":"A trident partially buried in the sand","roll":37,"Level":"11-16"},
    {"Encounter":"A trident partially buried in the sand","roll":38,"Level":"11-16"},
    {"Encounter":"A trident partially buried in the sand","roll":39,"Level":"11-16"},
    {"Encounter":"A trident partially buried in the sand","roll":40,"Level":"11-16"},
    {"Encounter":"1 young bronze dragon","roll":41,"Level":"11-16"},
    {"Encounter":"1 young bronze dragon","roll":42,"Level":"11-16"},
    {"Encounter":"1 young bronze dragon","roll":43,"Level":"11-16"},
    {"Encounter":"1 young bronze dragon","roll":44,"Level":"11-16"},
    {"Encounter":"1 young bronze dragon","roll":45,"Level":"11-16"},
    {"Encounter":"1 young bronze dragon","roll":46,"Level":"11-16"},
    {"Encounter":"1 young bronze dragon","roll":47,"Level":"11-16"},
    {"Encounter":"1 young bronze dragon","roll":48,"Level":"11-16"},
    {"Encounter":"1 young bronze dragon","roll":49,"Level":"11-16"},
    {"Encounter":"1 young bronze dragon","roll":50,"Level":"11-16"},
    {"Encounter":"1 marid","roll":51,"Level":"11-16"},
    {"Encounter":"1 marid","roll":52,"Level":"11-16"},
    {"Encounter":"1 marid","roll":53,"Level":"11-16"},
    {"Encounter":"1 marid","roll":54,"Level":"11-16"},
    {"Encounter":"1 marid","roll":55,"Level":"11-16"},
    {"Encounter":"1d6 water elementals","roll":56,"Level":"11-16"},
    {"Encounter":"1d6 water elementals","roll":57,"Level":"11-16"},
    {"Encounter":"1d6 water elementals","roll":58,"Level":"11-16"},
    {"Encounter":"1d6 water elementals","roll":59,"Level":"11-16"},
    {"Encounter":"1d6 water elementals","roll":60,"Level":"11-16"},
    {"Encounter":"2d6 ghasts crawling over 1d6 wrecked ships and feeding on the dead","roll":61,"Level":"11-16"},
    {"Encounter":"2d6 ghasts crawling over 1d6 wrecked ships and feeding on the dead","roll":62,"Level":"11-16"},
    {"Encounter":"2d6 ghasts crawling over 1d6 wrecked ships and feeding on the dead","roll":63,"Level":"11-16"},
    {"Encounter":"2d6 ghasts crawling over 1d6 wrecked ships and feeding on the dead","roll":64,"Level":"11-16"},
    {"Encounter":"2d6 ghasts crawling over 1d6 wrecked ships and feeding on the dead","roll":65,"Level":"11-16"},
    {"Encounter":"1 djinni","roll":66,"Level":"11-16"},
    {"Encounter":"1 djinni","roll":67,"Level":"11-16"},
    {"Encounter":"1 djinni","roll":68,"Level":"11-16"},
    {"Encounter":"1 djinni","roll":69,"Level":"11-16"},
    {"Encounter":"1 djinni","roll":70,"Level":"11-16"},
    {"Encounter":"1d3 young bronze dragons","roll":71,"Level":"11-16"},
    {"Encounter":"1d3 young bronze dragons","roll":72,"Level":"11-16"},
    {"Encounter":"1d3 young bronze dragons","roll":73,"Level":"11-16"},
    {"Encounter":"1d3 young bronze dragons","roll":74,"Level":"11-16"},
    {"Encounter":"1d3 young bronze dragons","roll":75,"Level":"11-16"},
    {"Encounter":"A beached whale, dead and bloated. If it takes any damage, it explodes, and each creature within 30 feet of it must make a DC 15 Dexterity saving throw, taking 5d6 bludgeoning damage on a failed save, or half as much damage on a successful one.","roll":76,"Level":"11-16"},
    {"Encounter":"A beached whale, dead and bloated. If it takes any damage, it explodes, and each creature within 30 feet of it must make a DC 15 Dexterity saving throw, taking 5d6 bludgeoning damage on a failed save, or half as much damage on a successful one.","roll":77,"Level":"11-16"},
    {"Encounter":"A beached whale, dead and bloated. If it takes any damage, it explodes, and each creature within 30 feet of it must make a DC 15 Dexterity saving throw, taking 5d6 bludgeoning damage on a failed save, or half as much damage on a successful one.","roll":78,"Level":"11-16"},
    {"Encounter":"A beached whale, dead and bloated. If it takes any damage, it explodes, and each creature within 30 feet of it must make a DC 15 Dexterity saving throw, taking 5d6 bludgeoning damage on a failed save, or half as much damage on a successful one.","roll":79,"Level":"11-16"},
    {"Encounter":"A beached whale, dead and bloated. If it takes any damage, it explodes, and each creature within 30 feet of it must make a DC 15 Dexterity saving throw, taking 5d6 bludgeoning damage on a failed save, or half as much damage on a successful one.","roll":80,"Level":"11-16"},
    {"Encounter":"2d4 cyclopes","roll":81,"Level":"11-16"},
    {"Encounter":"2d4 cyclopes","roll":82,"Level":"11-16"},
    {"Encounter":"1 storm giant","roll":83,"Level":"11-16"},
    {"Encounter":"1 storm giant","roll":84,"Level":"11-16"},
    {"Encounter":"1d3 young blue dragons","roll":85,"Level":"11-16"},
    {"Encounter":"1d3 young blue dragons","roll":86,"Level":"11-16"},
    {"Encounter":"1 adult bronze dragon","roll":87,"Level":"11-16"},
    {"Encounter":"1 adult bronze dragon","roll":88,"Level":"11-16"},
    {"Encounter":"1 adult blue dragon","roll":89,"Level":"11-16"},
    {"Encounter":"1 adult blue dragon","roll":90,"Level":"11-16"},
    {"Encounter":"1d3 rocs","roll":91,"Level":"11-16"},
    {"Encounter":"1d3 rocs","roll":92,"Level":"11-16"},
    {"Encounter":"1d3 rocs","roll":93,"Level":"11-16"},
    {"Encounter":"1 dragon turtle","roll":94,"Level":"11-16"},
    {"Encounter":"1 dragon turtle","roll":95,"Level":"11-16"},
    {"Encounter":"1 dragon turtle","roll":96,"Level":"11-16"},
    {"Encounter":"1 dragon turtle","roll":97,"Level":"11-16"},
    {"Encounter":"1 ancient bronze dragon","roll":98,"Level":"11-16"},
    {"Encounter":"1 ancient bronze dragon","roll":99,"Level":"11-16"},
    {"Encounter":"1 ancient blue dragon","roll":100,"Level":"11-16"},
    {"Encounter":"1 roc","roll":1,"Level":"17-20"},
    {"Encounter":"1 roc","roll":2,"Level":"17-20"},
    {"Encounter":"1 roc","roll":3,"Level":"17-20"},
    {"Encounter":"1 roc","roll":4,"Level":"17-20"},
    {"Encounter":"1 roc","roll":5,"Level":"17-20"},
    {"Encounter":"1 roc","roll":6,"Level":"17-20"},
    {"Encounter":"1 roc","roll":7,"Level":"17-20"},
    {"Encounter":"1 roc","roll":8,"Level":"17-20"},
    {"Encounter":"1 roc","roll":9,"Level":"17-20"},
    {"Encounter":"1 roc","roll":10,"Level":"17-20"},
    {"Encounter":"1 storm giant","roll":11,"Level":"17-20"},
    {"Encounter":"1 storm giant","roll":12,"Level":"17-20"},
    {"Encounter":"1 storm giant","roll":13,"Level":"17-20"},
    {"Encounter":"1 storm giant","roll":14,"Level":"17-20"},
    {"Encounter":"1 storm giant","roll":15,"Level":"17-20"},
    {"Encounter":"1 storm giant","roll":16,"Level":"17-20"},
    {"Encounter":"1 storm giant","roll":17,"Level":"17-20"},
    {"Encounter":"1 storm giant","roll":18,"Level":"17-20"},
    {"Encounter":"1 storm giant","roll":19,"Level":"17-20"},
    {"Encounter":"1 storm giant","roll":20,"Level":"17-20"},
    {"Encounter":"An adult bronze dragon fighting an adult blue dragon to the death","roll":21,"Level":"17-20"},
    {"Encounter":"An adult bronze dragon fighting an adult blue dragon to the death","roll":22,"Level":"17-20"},
    {"Encounter":"An adult bronze dragon fighting an adult blue dragon to the death","roll":23,"Level":"17-20"},
    {"Encounter":"An adult bronze dragon fighting an adult blue dragon to the death","roll":24,"Level":"17-20"},
    {"Encounter":"An adult bronze dragon fighting an adult blue dragon to the death","roll":25,"Level":"17-20"},
    {"Encounter":"2d4 cyclopes","roll":26,"Level":"17-20"},
    {"Encounter":"2d4 cyclopes","roll":27,"Level":"17-20"},
    {"Encounter":"2d4 cyclopes","roll":28,"Level":"17-20"},
    {"Encounter":"2d4 cyclopes","roll":29,"Level":"17-20"},
    {"Encounter":"2d4 cyclopes","roll":30,"Level":"17-20"},
    {"Encounter":"2d4 cyclopes","roll":31,"Level":"17-20"},
    {"Encounter":"2d4 cyclopes","roll":32,"Level":"17-20"},
    {"Encounter":"2d4 cyclopes","roll":33,"Level":"17-20"},
    {"Encounter":"2d4 cyclopes","roll":34,"Level":"17-20"},
    {"Encounter":"2d4 cyclopes","roll":35,"Level":"17-20"},
    {"Encounter":"2d4 cyclopes","roll":36,"Level":"17-20"},
    {"Encounter":"2d4 cyclopes","roll":37,"Level":"17-20"},
    {"Encounter":"2d4 cyclopes","roll":38,"Level":"17-20"},
    {"Encounter":"2d4 cyclopes","roll":39,"Level":"17-20"},
    {"Encounter":"2d4 cyclopes","roll":40,"Level":"17-20"},
    {"Encounter":"1 adult bronze dragon or 1 adult blue dragon","roll":41,"Level":"17-20"},
    {"Encounter":"1 adult bronze dragon or 1 adult blue dragon","roll":42,"Level":"17-20"},
    {"Encounter":"1 adult bronze dragon or 1 adult blue dragon","roll":43,"Level":"17-20"},
    {"Encounter":"1 adult bronze dragon or 1 adult blue dragon","roll":44,"Level":"17-20"},
    {"Encounter":"1 adult bronze dragon or 1 adult blue dragon","roll":45,"Level":"17-20"},
    {"Encounter":"1 adult bronze dragon or 1 adult blue dragon","roll":46,"Level":"17-20"},
    {"Encounter":"1 adult bronze dragon or 1 adult blue dragon","roll":47,"Level":"17-20"},
    {"Encounter":"1 adult bronze dragon or 1 adult blue dragon","roll":48,"Level":"17-20"},
    {"Encounter":"1 adult bronze dragon or 1 adult blue dragon","roll":49,"Level":"17-20"},
    {"Encounter":"1 adult bronze dragon or 1 adult blue dragon","roll":50,"Level":"17-20"},
    {"Encounter":"1d3 djinni or 1d3 marids","roll":51,"Level":"17-20"},
    {"Encounter":"1d3 djinni or 1d3 marids","roll":52,"Level":"17-20"},
    {"Encounter":"1d3 djinni or 1d3 marids","roll":53,"Level":"17-20"},
    {"Encounter":"1d3 djinni or 1d3 marids","roll":54,"Level":"17-20"},
    {"Encounter":"1d3 djinni or 1d3 marids","roll":55,"Level":"17-20"},
    {"Encounter":"1d3 djinni or 1d3 marids","roll":56,"Level":"17-20"},
    {"Encounter":"1d3 djinni or 1d3 marids","roll":57,"Level":"17-20"},
    {"Encounter":"1d3 djinni or 1d3 marids","roll":58,"Level":"17-20"},
    {"Encounter":"1d3 djinni or 1d3 marids","roll":59,"Level":"17-20"},
    {"Encounter":"1d3 djinni or 1d3 marids","roll":60,"Level":"17-20"},
    {"Encounter":"1 dragon turtle","roll":61,"Level":"17-20"},
    {"Encounter":"1 dragon turtle","roll":62,"Level":"17-20"},
    {"Encounter":"1 dragon turtle","roll":63,"Level":"17-20"},
    {"Encounter":"1 dragon turtle","roll":64,"Level":"17-20"},
    {"Encounter":"1 dragon turtle","roll":65,"Level":"17-20"},
    {"Encounter":"1 dragon turtle","roll":66,"Level":"17-20"},
    {"Encounter":"1 dragon turtle","roll":67,"Level":"17-20"},
    {"Encounter":"1 dragon turtle","roll":68,"Level":"17-20"},
    {"Encounter":"1 dragon turtle","roll":69,"Level":"17-20"},
    {"Encounter":"1 dragon turtle","roll":70,"Level":"17-20"},
    {"Encounter":"1d3 rocs","roll":71,"Level":"17-20"},
    {"Encounter":"1d3 rocs","roll":72,"Level":"17-20"},
    {"Encounter":"1d3 rocs","roll":73,"Level":"17-20"},
    {"Encounter":"1d3 rocs","roll":74,"Level":"17-20"},
    {"Encounter":"1d3 rocs","roll":75,"Level":"17-20"},
    {"Encounter":"1d6+2 waterspouts that dance on the water before stopping abruptly","roll":76,"Level":"17-20"},
    {"Encounter":"1d6+2 waterspouts that dance on the water before stopping abruptly","roll":77,"Level":"17-20"},
    {"Encounter":"1d6+2 waterspouts that dance on the water before stopping abruptly","roll":78,"Level":"17-20"},
    {"Encounter":"1d6+2 waterspouts that dance on the water before stopping abruptly","roll":79,"Level":"17-20"},
    {"Encounter":"1d6+2 waterspouts that dance on the water before stopping abruptly","roll":80,"Level":"17-20"},
    {"Encounter":"1d6 young blue dragons","roll":81,"Level":"17-20"},
    {"Encounter":"1d6 young blue dragons","roll":82,"Level":"17-20"},
    {"Encounter":"1d6 young blue dragons","roll":83,"Level":"17-20"},
    {"Encounter":"1d6 young blue dragons","roll":84,"Level":"17-20"},
    {"Encounter":"1d6 young blue dragons","roll":85,"Level":"17-20"},
    {"Encounter":"1d6 young blue dragons","roll":86,"Level":"17-20"},
    {"Encounter":"1d6 young blue dragons","roll":87,"Level":"17-20"},
    {"Encounter":"1d6 young blue dragons","roll":88,"Level":"17-20"},
    {"Encounter":"1d6 young blue dragons","roll":89,"Level":"17-20"},
    {"Encounter":"1d6 young blue dragons","roll":90,"Level":"17-20"},
    {"Encounter":"1 ancient bronze dragon","roll":91,"Level":"17-20"},
    {"Encounter":"1 ancient bronze dragon","roll":92,"Level":"17-20"},
    {"Encounter":"1 ancient bronze dragon","roll":93,"Level":"17-20"},
    {"Encounter":"1 ancient bronze dragon","roll":94,"Level":"17-20"},
    {"Encounter":"1 ancient bronze dragon","roll":95,"Level":"17-20"},
    {"Encounter":"1 ancient bronze dragon","roll":96,"Level":"17-20"},
    {"Encounter":"1 ancient blue dragon","roll":97,"Level":"17-20"},
    {"Encounter":"1 ancient blue dragon","roll":98,"Level":"17-20"},
    {"Encounter":"1 ancient blue dragon","roll":99,"Level":"17-20"},
    {"Encounter":"1d3+1 storm giants","roll":100,"Level":"17-20"},
    {"Encounter":"2d8 giant wolf spiders","roll":1,"Level":"5-10"},
    {"Encounter":"3d6 pteranodons","roll":2,"Level":"5-10"},
    {"Encounter":"3d6 pteranodons","roll":3,"Level":"5-10"},
    {"Encounter":"2d4 scouts","roll":4,"Level":"5-10"},
    {"Encounter":"2d4 scouts","roll":5,"Level":"5-10"},
    {"Encounter":"1d6+2 sahuagin","roll":6,"Level":"5-10"},
    {"Encounter":"1d6+2 sahuagin","roll":7,"Level":"5-10"},
    {"Encounter":"1 sea hag","roll":8,"Level":"5-10"},
    {"Encounter":"1d4+1 giant toads","roll":9,"Level":"5-10"},
    {"Encounter":"1d4+1 giant toads","roll":10,"Level":"5-10"},
    {"Encounter":"3d6 sahuagin","roll":11,"Level":"5-10"},
    {"Encounter":"3d6 sahuagin","roll":12,"Level":"5-10"},
    {"Encounter":"3d6 sahuagin","roll":13,"Level":"5-10"},
    {"Encounter":"3d6 sahuagin","roll":14,"Level":"5-10"},
    {"Encounter":"3d6 sahuagin","roll":15,"Level":"5-10"},
    {"Encounter":"2d6 giant eagles","roll":16,"Level":"5-10"},
    {"Encounter":"2d6 giant eagles","roll":17,"Level":"5-10"},
    {"Encounter":"2d6 giant eagles","roll":18,"Level":"5-10"},
    {"Encounter":"2d6 giant eagles","roll":19,"Level":"5-10"},
    {"Encounter":"2d6 giant eagles","roll":20,"Level":"5-10"},
    {"Encounter":"A pseudodragon chasing gulls through the air","roll":21,"Level":"5-10"},
    {"Encounter":"A pseudodragon chasing gulls through the air","roll":22,"Level":"5-10"},
    {"Encounter":"A pseudodragon chasing gulls through the air","roll":23,"Level":"5-10"},
    {"Encounter":"A pseudodragon chasing gulls through the air","roll":24,"Level":"5-10"},
    {"Encounter":"A pseudodragon chasing gulls through the air","roll":25,"Level":"5-10"},
    {"Encounter":"1d2 druids","roll":26,"Level":"5-10"},
    {"Encounter":"1d2 druids","roll":27,"Level":"5-10"},
    {"Encounter":"1d2 druids","roll":28,"Level":"5-10"},
    {"Encounter":"1d2 druids","roll":29,"Level":"5-10"},
    {"Encounter":"2d4+1 giant toads","roll":30,"Level":"5-10"},
    {"Encounter":"2d4+1 giant toads","roll":31,"Level":"5-10"},
    {"Encounter":"2d4+1 giant toads","roll":32,"Level":"5-10"},
    {"Encounter":"1 commoner singing a dirge (day only) or 1 banshee (night only)","roll":33,"Level":"5-10"},
    {"Encounter":"1 commoner singing a dirge (day only) or 1 banshee (night only)","roll":34,"Level":"5-10"},
    {"Encounter":"1 commoner singing a dirge (day only) or 1 banshee (night only)","roll":35,"Level":"5-10"},
    {"Encounter":"A stoppered bottle containing an illegible note and half buried in the sand","roll":36,"Level":"5-10"},
    {"Encounter":"A stoppered bottle containing an illegible note and half buried in the sand","roll":37,"Level":"5-10"},
    {"Encounter":"A stoppered bottle containing an illegible note and half buried in the sand","roll":38,"Level":"5-10"},
    {"Encounter":"A stoppered bottle containing an illegible note and half buried in the sand","roll":39,"Level":"5-10"},
    {"Encounter":"A stoppered bottle containing an illegible note and half buried in the sand","roll":40,"Level":"5-10"},
    {"Encounter":"3 sea hags","roll":41,"Level":"5-10"},
    {"Encounter":"3 sea hags","roll":42,"Level":"5-10"},
    {"Encounter":"3 sea hags","roll":43,"Level":"5-10"},
    {"Encounter":"1d8+1 harpies","roll":44,"Level":"5-10"},
    {"Encounter":"1d8+1 harpies","roll":45,"Level":"5-10"},
    {"Encounter":"1d8+1 harpies","roll":46,"Level":"5-10"},
    {"Encounter":"1d4 plesiosauruses","roll":47,"Level":"5-10"},
    {"Encounter":"1d4 plesiosauruses","roll":48,"Level":"5-10"},
    {"Encounter":"1d4 plesiosauruses","roll":49,"Level":"5-10"},
    {"Encounter":"1d4 plesiosauruses","roll":50,"Level":"5-10"},
    {"Encounter":"1d4 manticores","roll":51,"Level":"5-10"},
    {"Encounter":"1d4 manticores","roll":52,"Level":"5-10"},
    {"Encounter":"1d4 manticores","roll":53,"Level":"5-10"},
    {"Encounter":"2d4 ogres","roll":54,"Level":"5-10"},
    {"Encounter":"2d4 ogres","roll":55,"Level":"5-10"},
    {"Encounter":"2d4 ogres","roll":56,"Level":"5-10"},
    {"Encounter":"1d10 griffons","roll":57,"Level":"5-10"},
    {"Encounter":"1d10 griffons","roll":58,"Level":"5-10"},
    {"Encounter":"1d10 griffons","roll":59,"Level":"5-10"},
    {"Encounter":"1d10 griffons","roll":60,"Level":"5-10"},
    {"Encounter":"A battle at sea between two galleons","roll":61,"Level":"5-10"},
    {"Encounter":"A battle at sea between two galleons","roll":62,"Level":"5-10"},
    {"Encounter":"A battle at sea between two galleons","roll":63,"Level":"5-10"},
    {"Encounter":"A battle at sea between two galleons","roll":64,"Level":"5-10"},
    {"Encounter":"A battle at sea between two galleons","roll":65,"Level":"5-10"},
    {"Encounter":"1d4+3 merrow","roll":66,"Level":"5-10"},
    {"Encounter":"1d4+3 merrow","roll":67,"Level":"5-10"},
    {"Encounter":"1d4+3 merrow","roll":68,"Level":"5-10"},
    {"Encounter":"1d4+3 merrow","roll":69,"Level":"5-10"},
    {"Encounter":"1d4+3 merrow","roll":70,"Level":"5-10"},
    {"Encounter":"A pirate crew consisting of 1 bandit captain, 1 druid, 2 berserkers, and 2d12 bandits, all searching for buried treasure","roll":71,"Level":"5-10"},
    {"Encounter":"A pirate crew consisting of 1 bandit captain, 1 druid, 2 berserkers, and 2d12 bandits, all searching for buried treasure","roll":72,"Level":"5-10"},
    {"Encounter":"A pirate crew consisting of 1 bandit captain, 1 druid, 2 berserkers, and 2d12 bandits, all searching for buried treasure","roll":73,"Level":"5-10"},
    {"Encounter":"A pirate crew consisting of 1 bandit captain, 1 druid, 2 berserkers, and 2d12 bandits, all searching for buried treasure","roll":74,"Level":"5-10"},
    {"Encounter":"A pirate crew consisting of 1 bandit captain, 1 druid, 2 berserkers, and 2d12 bandits, all searching for buried treasure","roll":75,"Level":"5-10"},
    {"Encounter":"A severed humanoid hand tangled in a net","roll":76,"Level":"5-10"},
    {"Encounter":"A severed humanoid hand tangled in a net","roll":77,"Level":"5-10"},
    {"Encounter":"A severed humanoid hand tangled in a net","roll":78,"Level":"5-10"},
    {"Encounter":"A severed humanoid hand tangled in a net","roll":79,"Level":"5-10"},
    {"Encounter":"A severed humanoid hand tangled in a net","roll":80,"Level":"5-10"},
    {"Encounter":"1 water elemental","roll":81,"Level":"5-10"},
    {"Encounter":"1 water elemental","roll":82,"Level":"5-10"},
    {"Encounter":"1 cyclops","roll":83,"Level":"5-10"},
    {"Encounter":"1 cyclops","roll":84,"Level":"5-10"},
    {"Encounter":"1d4 banshees (night only)","roll":85,"Level":"5-10"},
    {"Encounter":"1d4 banshees (night only)","roll":86,"Level":"5-10"},
    {"Encounter":"2d4 veterans","roll":87,"Level":"5-10"},
    {"Encounter":"2d4 veterans","roll":88,"Level":"5-10"},
    {"Encounter":"1 young bronze dragon","roll":89,"Level":"5-10"},
    {"Encounter":"1 young bronze dragon","roll":90,"Level":"5-10"},
    {"Encounter":"1d3 cyclopes","roll":91,"Level":"5-10"},
    {"Encounter":"1d3 cyclopes","roll":92,"Level":"5-10"},
    {"Encounter":"1d3 cyclopes","roll":93,"Level":"5-10"},
    {"Encounter":"1 young blue dragon","roll":94,"Level":"5-10"},
    {"Encounter":"1 young blue dragon","roll":95,"Level":"5-10"},
    {"Encounter":"1 sahuagin baron with 1d3 sahuagin priestesses and 2d8 sahuagin","roll":96,"Level":"5-10"},
    {"Encounter":"1 djinni","roll":97,"Level":"5-10"},
    {"Encounter":"1 roc","roll":98,"Level":"5-10"},
    {"Encounter":"1 marid","roll":99,"Level":"5-10"},
    {"Encounter":"1 storm giant","roll":100,"Level":"5-10"}
]
let desert = 