let tableNPCSex = [{"d3":1,"sex":"male"},
{"d3":2,"sex":"female"},
{"d3":3,"sex":"intersex"}]

let tableNPCGender = [{"d6":1,"gender":"male"},
{"d6":2,"gender":"female"},
{"d6":3,"gender":"non-binary"},
{"d6":4,"gender":"transgender"},
{"d6":5,"gender":"agender"},
{"d6":6,"gender":"genderfluid"}]

let tableNPCSexualOrientation = [{"d6":1,"sexual_orientation":"heterosexual"},
{"d6":2,"sexual_orientation":"homosexual"},
{"d6":3,"sexual_orientation":"bisexual"},
{"d6":4,"sexual_orientation":"pansexual"},
{"d6":5,"sexual_orientation":"asexual"},
{"d6":6,"sexual_orientation":"sapiosexual"}]

let tableNPCRelationshipOrientation = [{"d2":1,"relationship_orientation":"monoamorous"},
{"d2":2,"relationship_orientation":"polyamorous"}]

let tableNPCAlignment = [{"d9":1,"alignment":"lawful good"},
{"d9":2,"alignment":"neutral good"},
{"d9":3,"alignment":"chaotic good"},
{"d9":4,"alignment":"lawful  neutral"},
{"d9":5,"alignment":"true neutral"},
{"d9":6,"alignment":"chaotic neutral"},
{"d9":7,"alignment":"lawful evil"},
{"d9":8,"alignment":"neutra evil"},
{"d9":9,"alignment":"chaotic evil"}]

let tableNPCBodyShapeFemale = [{"d5":1,"body_shape_female":"rectangle"},
{"d5":2,"body_shape_female":"triangle"},
{"d5":3,"body_shape_female":"hourglass"},
{"d5":4,"body_shape_female":"inverted triangle"},
{"d5":5,"body_shape_female":"round"}]

let tableNPCBodyShapeMale = [{"d5":1,"body_shape_male":"oval"},
{"d5":2,"body_shape_male":"triangle"},
{"d5":3,"body_shape_male":"rectangle"},
{"d5":4,"body_shape_male":"rhomboid"},
{"d5":5,"body_shape_male":"inverted triangle"}]

let tableNPCRelationshipStatusMonoamorous = [{"d12":1,"relationship_status_monoamorous":"married"},
{"d12":2,"relationship_status_monoamorous":"in a relationship"},
{"d12":3,"relationship_status_monoamorous":"single and looking"},
{"d12":4,"relationship_status_monoamorous":"single and not looking"},
{"d12":5,"relationship_status_monoamorous":"divorced"},
{"d12":6,"relationship_status_monoamorous":"widowed"},
{"d12":7,"relationship_status_monoamorous":"recently broke up"},
{"d12":8,"relationship_status_monoamorous":"recently divorced"},
{"d12":9,"relationship_status_monoamorous":"recently widowed"},
{"d12":10,"relationship_status_monoamorous":"recently separated"},
{"d12":11,"relationship_status_monoamorous":"seeing someone who is married"},
{"d12":12,"relationship_status_monoamorous":"married and having an affair"}]

let tableNPCRelationshipStatusPolyamorour = [{"d12":1,"relationship_status_polyamorous":"married to 2d6 others"},
{"d12":2,"relationship_status_polyamorous":"in a relationship with 2d6 others"},
{"d12":3,"relationship_status_polyamorous":"single and looking"},
{"d12":4,"relationship_status_polyamorous":"single and not looking"},
{"d12":5,"relationship_status_polyamorous":"divorced from 2d6 others"},
{"d12":6,"relationship_status_polyamorous":"widowed from 2d6 others"},
{"d12":7,"relationship_status_polyamorous":"recently broke up with 2d6 others"},
{"d12":8,"relationship_status_polyamorous":"recently divorced from 2d6 otheres"},
{"d12":9,"relationship_status_polyamorous":"recently widowed by 2d6 others"},
{"d12":10,"relationship_status_polyamorous":"recently separated from 2d6 others"},
{"d12":11,"relationship_status_polyamorous":"seeing 2d6 others and 1d4 monamorous individuals"},
{"d12":12,"relationship_status_polyamorous":"seeing 2d6 others and having an affair with 1d4 others"}]

let tableNPCBodyType = [{"d8":1,"body_type":"thin"},
{"d8":2,"body_type":"overweight"},
{"d8":3,"body_type":"average"},
{"d8":4,"body_type":"fit"},
{"d8":5,"body_type":"jacked"},
{"d8":6,"body_type":"a little extra"},
{"d8":7,"body_type":"curvy"},
{"d8":8,"body_type":"full figured"}]

let tableNPCPregnantStatus = [{"d20":"1-19","pregnant_status":"not pregnant"},
{"d20":"20","pregnant_status":"pregnant"}]

let tableNPCHairLength = [{"d15":1,"hair_length":"short"},
{"d15":2,"hair_length":"medium"},
{"d15":3,"hair_length":"neck length"},
{"d15":4,"hair_length":"shoulder length"},
{"d15":5,"hair_length":"armpit length"},
{"d15":6,"hair_length":"middle back length"},
{"d15":7,"hair_length":"waist length"},
{"d15":8,"hair_length":"hip length"},
{"d15":9,"hair_length":"tailbone length"},
{"d15":10,"hair_length":"butt length"},
{"d15":11,"hair_length":"mid-thigh length"},
{"d15":12,"hair_length":"knee length"},
{"d15":13,"hair_length":"calf length"},
{"d15":14,"hair_length":"ankle length"},
{"d15":15,"hair_length":"floor length"}]

let tableNPCHairType = [{"d12":1,"hair_type":"bone straight"},
{"d12":2,"hair_type":"straight and delicately wavy"},
{"d12":3,"hair_type":"slightly wavy"},
{"d12":4,"hair_type":"beachy wavy"},
{"d12":5,"hair_type":"medium wavy"},
{"d12":6,"hair_type":"loose curly"},
{"d12":7,"hair_type":"slightly curly"},
{"d12":8,"hair_type":"medium curly"},
{"d12":9,"hair_type":"super curly"},
{"d12":10,"hair_type":"slightly kinky"},
{"d12":11,"hair_type":"kinky"},
{"d12":12,"hair_type":"coily"}]

let tableNPCFaceShape = [{"d9":1,"face_shape":"long"},
{"d9":2,"face_shape":"rectangle"},
{"d9":3,"face_shape":"circle"},
{"d9":4,"face_shape":"square"},
{"d9":5,"face_shape":"inverse triangle"},
{"d9":6,"face_shape":"heart"},
{"d9":7,"face_shape":"diamond"},
{"d9":8,"face_shape":"triangle"},
{"d9":9,"face_shape":"oval"}]

let tableNPCEyeColor = [{"d25":1,"eye_color":"agate"},
{"d25":2,"eye_color":"baby blue"},
{"d25":3,"eye_color":"old world blue"},
{"d25":4,"eye_color":"dream"},
{"d25":5,"eye_color":"serene"},
{"d25":6,"eye_color":"blue star"},
{"d25":7,"eye_color":"nordic"},
{"d25":8,"eye_color":"cobalt"},
{"d25":9,"eye_color":"hazel"},
{"d25":10,"eye_color":"azure"},
{"d25":11,"eye_color":"lapis"},
{"d25":12,"eye_color":"liz"},
{"d25":13,"eye_color":"creole iris"},
{"d25":14,"eye_color":"forest"},
{"d25":15,"eye_color":"vale"},
{"d25":16,"eye_color":"nomad"},
{"d25":17,"eye_color":"frisco"},
{"d25":18,"eye_color":"rain cloud"},
{"d25":19,"eye_color":"winter grey"},
{"d25":20,"eye_color":"chuck hazel"},
{"d25":21,"eye_color":"toasty topaz"},
{"d25":22,"eye_color":"teak wood"},
{"d25":23,"eye_color":"sable"},
{"d25":24,"eye_color":"paris brun"},
{"d25":25,"eye_color":"ebony"}]

let tableNPCHairColor = [{"d56":1,"hair_color":"perugia black"},
{"d56":2,"hair_color":"pescara black"},
{"d56":3,"hair_color":"parma black"},
{"d56":4,"hair_color":"positano black"},
{"d56":5,"hair_color":"palermo black"},
{"d56":6,"hair_color":"ravenna brown"},
{"d56":7,"hair_color":"messina brown"},
{"d56":8,"hair_color":"venezia brown"},
{"d56":9,"hair_color":"bolzano brown"},
{"d56":10,"hair_color":"volterra amethyst"},
{"d56":11,"hair_color":"barletta brown"},
{"d56":12,"hair_color":"torino brown"},
{"d56":13,"hair_color":"milano brown"},
{"d56":14,"hair_color":"napoli brown"},
{"d56":15,"hair_color":"trieste red"},
{"d56":16,"hair_color":"catania brown"},
{"d56":17,"hair_color":"rimini garnet"},
{"d56":18,"hair_color":"dosolo brown"},
{"d56":19,"hair_color":"modena brown"},
{"d56":20,"hair_color":"zocca brown"},
{"d56":21,"hair_color":"siena brown"},
{"d56":22,"hair_color":"verona brown"},
{"d56":23,"hair_color":"sardinia red"},
{"d56":24,"hair_color":"portofino red"},
{"d56":25,"hair_color":"tuscany brown"},
{"d56":26,"hair_color":"firenze brown"},
{"d56":27,"hair_color":"savona scarlet"},
{"d56":28,"hair_color":"sondrio brown"},
{"d56":29,"hair_color":"novara light brown"},
{"d56":30,"hair_color":"avella light brown"},
{"d56":31,"hair_color":"veneto light brown"},
{"d56":32,"hair_color":"vesuvius red"},
{"d56":33,"hair_color":"genova red"},
{"d56":34,"hair_color":"lucca light brown"},
{"d56":35,"hair_color":"como light brown"},
{"d56":36,"hair_color":"carrara crimson"},
{"d56":37,"hair_color":"umbria light brown"},
{"d56":38,"hair_color":"granara blonde"},
{"d56":39,"hair_color":"tivoli blonde"},
{"d56":40,"hair_color":"bologna blonde"},
{"d56":41,"hair_color":"sicily blonde"},
{"d56":42,"hair_color":"ravello blonde"},
{"d56":43,"hair_color":"matera marigold"},
{"d56":44,"hair_color":"lusia dark blonde"},
{"d56":45,"hair_color":"termoli blonde"},
{"d56":46,"hair_color":"nocera blonde"},
{"d56":47,"hair_color":"pisa blonde"},
{"d56":48,"hair_color":"varese blonde"},
{"d56":49,"hair_color":"tremiti blonde"},
{"d56":50,"hair_color":"capri blonde"},
{"d56":51,"hair_color":"manarola blonde"},
{"d56":52,"hair_color":"roma blonde"},
{"d56":53,"hair_color":"amalfi blonde"},
{"d56":54,"hair_color":"prato ash"},
{"d56":55,"hair_color":"ancona natural"},
{"d56":56,"hair_color":"ferrara golden"}]

let tableNPCRace = [{"d96":1,"RACE":"Aarakocra","BASE_HEIGHT_IN":52,"HEIGHT_MOD":"2d8","BASE_WEIGHT_LBS":50,"WEIGHT_MOD":"1d6","AGE_LEB":30,"AGE_ADULT":3},
{"d96":2,"RACE":"Aasimar (Fallen)","BASE_HEIGHT_IN":56,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":160,"AGE_ADULT":25},
{"d96":3,"RACE":"Aasimar (Protector)","BASE_HEIGHT_IN":56,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":160,"AGE_ADULT":25},
{"d96":4,"RACE":"Aasimar (Scourge)","BASE_HEIGHT_IN":56,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":160,"AGE_ADULT":25},
{"d96":5,"RACE":"Bugbear","BASE_HEIGHT_IN":72,"HEIGHT_MOD":"2d12","BASE_WEIGHT_LBS":200,"WEIGHT_MOD":"2d6","AGE_LEB":80,"AGE_ADULT":16},
{"d96":6,"RACE":"Centaur","BASE_HEIGHT_IN":72,"HEIGHT_MOD":"1d10","BASE_WEIGHT_LBS":600,"WEIGHT_MOD":"2d12","AGE_LEB":100,"AGE_ADULT":25},
{"d96":7,"RACE":"Changeling","BASE_HEIGHT_IN":61,"HEIGHT_MOD":"2d4","BASE_WEIGHT_LBS":115,"WEIGHT_MOD":"2d4","AGE_LEB":100,"AGE_ADULT":25},
{"d96":8,"RACE":"Dragonborn (Base)","BASE_HEIGHT_IN":66,"HEIGHT_MOD":"2d8","BASE_WEIGHT_LBS":175,"WEIGHT_MOD":"2d6","AGE_LEB":80,"AGE_ADULT":15},
{"d96":9,"RACE":"Dragonborn (Draconblood)","BASE_HEIGHT_IN":66,"HEIGHT_MOD":"2d8","BASE_WEIGHT_LBS":175,"WEIGHT_MOD":"2d6","AGE_LEB":80,"AGE_ADULT":15},
{"d96":10,"RACE":"Dragonborn (Ravenite)","BASE_HEIGHT_IN":66,"HEIGHT_MOD":"2d8","BASE_WEIGHT_LBS":175,"WEIGHT_MOD":"2d6","AGE_LEB":80,"AGE_ADULT":15},
{"d96":11,"RACE":"Dwarf (Duergar)","BASE_HEIGHT_IN":48,"HEIGHT_MOD":"2d4","BASE_WEIGHT_LBS":120,"WEIGHT_MOD":"2d6","AGE_LEB":350,"AGE_ADULT":50},
{"d96":12,"RACE":"Dwarf (Hill)","BASE_HEIGHT_IN":44,"HEIGHT_MOD":"2d4","BASE_WEIGHT_LBS":115,"WEIGHT_MOD":"2d6","AGE_LEB":350,"AGE_ADULT":50},
{"d96":13,"RACE":"Dwarf (Mark of Warding)","BASE_HEIGHT_IN":44,"HEIGHT_MOD":"2d4","BASE_WEIGHT_LBS":115,"WEIGHT_MOD":"2d6","AGE_LEB":350,"AGE_ADULT":50},
{"d96":14,"RACE":"Dwarf (Mountain)","BASE_HEIGHT_IN":48,"HEIGHT_MOD":"2d4","BASE_WEIGHT_LBS":120,"WEIGHT_MOD":"2d6","AGE_LEB":350,"AGE_ADULT":50},
{"d96":15,"RACE":"Elf (Drow)","BASE_HEIGHT_IN":53,"HEIGHT_MOD":"2d6","BASE_WEIGHT_LBS":75,"WEIGHT_MOD":"1d6","AGE_LEB":750,"AGE_ADULT":25},
{"d96":16,"RACE":"Elf (Eladrin)","BASE_HEIGHT_IN":54,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":90,"WEIGHT_MOD":"1d4","AGE_LEB":750,"AGE_ADULT":25},
{"d96":17,"RACE":"Elf (High)","BASE_HEIGHT_IN":54,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":90,"WEIGHT_MOD":"1d4","AGE_LEB":750,"AGE_ADULT":25},
{"d96":18,"RACE":"Elf (Mark of Shadow)","BASE_HEIGHT_IN":54,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":90,"WEIGHT_MOD":"1d4","AGE_LEB":750,"AGE_ADULT":25},
{"d96":19,"RACE":"Elf (Pallid)","BASE_HEIGHT_IN":54,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":90,"WEIGHT_MOD":"1d4","AGE_LEB":750,"AGE_ADULT":25},
{"d96":20,"RACE":"Elf (Sea)","BASE_HEIGHT_IN":53,"HEIGHT_MOD":"2d6","BASE_WEIGHT_LBS":75,"WEIGHT_MOD":"1d6","AGE_LEB":750,"AGE_ADULT":25},
{"d96":21,"RACE":"Elf (Shadar-kai)","BASE_HEIGHT_IN":53,"HEIGHT_MOD":"2d6","BASE_WEIGHT_LBS":75,"WEIGHT_MOD":"1d6","AGE_LEB":750,"AGE_ADULT":25},
{"d96":22,"RACE":"Elf (Wood)","BASE_HEIGHT_IN":54,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":100,"WEIGHT_MOD":"1d4","AGE_LEB":750,"AGE_ADULT":25},
{"d96":23,"RACE":"Firbolg","BASE_HEIGHT_IN":74,"HEIGHT_MOD":"2d12","BASE_WEIGHT_LBS":175,"WEIGHT_MOD":"2d6","AGE_LEB":500,"AGE_ADULT":30},
{"d96":24,"RACE":"Genasi (Air)","BASE_HEIGHT_IN":56,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":120,"AGE_ADULT":25},
{"d96":25,"RACE":"Genasi (Earth)","BASE_HEIGHT_IN":56,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":120,"AGE_ADULT":25},
{"d96":26,"RACE":"Genasi (Fire)","BASE_HEIGHT_IN":56,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":120,"AGE_ADULT":25},
{"d96":27,"RACE":"Genasi (Water)","BASE_HEIGHT_IN":56,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":120,"AGE_ADULT":25},
{"d96":28,"RACE":"Gith (Githyanki)","BASE_HEIGHT_IN":60,"HEIGHT_MOD":"2d12","BASE_WEIGHT_LBS":100,"WEIGHT_MOD":"2d4","AGE_LEB":100,"AGE_ADULT":19},
{"d96":29,"RACE":"Gith (Githzerai)","BASE_HEIGHT_IN":59,"HEIGHT_MOD":"2d12","BASE_WEIGHT_LBS":90,"WEIGHT_MOD":"1d4","AGE_LEB":100,"AGE_ADULT":19},
{"d96":30,"RACE":"Gnome (Deep)","BASE_HEIGHT_IN":35,"HEIGHT_MOD":"2d4","BASE_WEIGHT_LBS":35,"WEIGHT_MOD":"1","AGE_LEB":500,"AGE_ADULT":25},
{"d96":31,"RACE":"Gnome (Deep/Svirfneblin)","BASE_HEIGHT_IN":35,"HEIGHT_MOD":"2d4","BASE_WEIGHT_LBS":35,"WEIGHT_MOD":"1","AGE_LEB":500,"AGE_ADULT":25},
{"d96":32,"RACE":"Gnome (Forest)","BASE_HEIGHT_IN":35,"HEIGHT_MOD":"2d4","BASE_WEIGHT_LBS":35,"WEIGHT_MOD":"1","AGE_LEB":500,"AGE_ADULT":25},
{"d96":33,"RACE":"Gnome (Mark of Scribing)","BASE_HEIGHT_IN":35,"HEIGHT_MOD":"2d4","BASE_WEIGHT_LBS":35,"WEIGHT_MOD":"1","AGE_LEB":500,"AGE_ADULT":25},
{"d96":34,"RACE":"Gnome (Rock)","BASE_HEIGHT_IN":35,"HEIGHT_MOD":"2d4","BASE_WEIGHT_LBS":35,"WEIGHT_MOD":"1","AGE_LEB":500,"AGE_ADULT":25},
{"d96":35,"RACE":"Goblin","BASE_HEIGHT_IN":41,"HEIGHT_MOD":"2d4","BASE_WEIGHT_LBS":35,"WEIGHT_MOD":"1","AGE_LEB":60,"AGE_ADULT":8},
{"d96":36,"RACE":"Goliath","BASE_HEIGHT_IN":74,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":200,"WEIGHT_MOD":"2d6","AGE_LEB":100,"AGE_ADULT":25},
{"d96":37,"RACE":"Half-Elf","BASE_HEIGHT_IN":57,"HEIGHT_MOD":"2d8","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":200,"AGE_ADULT":20},
{"d96":38,"RACE":"Half-Elf (Aquatic Elf Descent)","BASE_HEIGHT_IN":57,"HEIGHT_MOD":"2d8","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":200,"AGE_ADULT":20},
{"d96":39,"RACE":"Half-Elf (Drow Descent)","BASE_HEIGHT_IN":57,"HEIGHT_MOD":"2d8","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":200,"AGE_ADULT":20},
{"d96":40,"RACE":"Half-Elf (Mark of Detection)","BASE_HEIGHT_IN":57,"HEIGHT_MOD":"2d8","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":200,"AGE_ADULT":20},
{"d96":41,"RACE":"Half-Elf (Mark of Storm)","BASE_HEIGHT_IN":57,"HEIGHT_MOD":"2d8","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":200,"AGE_ADULT":20},
{"d96":42,"RACE":"Half-Elf (Moon Elf or Sun Elf Descent)","BASE_HEIGHT_IN":57,"HEIGHT_MOD":"2d8","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":200,"AGE_ADULT":20},
{"d96":43,"RACE":"Half-Elf (Wood Elf Descent)","BASE_HEIGHT_IN":57,"HEIGHT_MOD":"2d8","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":200,"AGE_ADULT":20},
{"d96":44,"RACE":"Half-Orc","BASE_HEIGHT_IN":58,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":140,"WEIGHT_MOD":"2d6","AGE_LEB":75,"AGE_ADULT":14},
{"d96":45,"RACE":"Half-Orc (Mark of Finding)","BASE_HEIGHT_IN":58,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":140,"WEIGHT_MOD":"2d6","AGE_LEB":75,"AGE_ADULT":14},
{"d96":46,"RACE":"Halfling","BASE_HEIGHT_IN":31,"HEIGHT_MOD":"2d4","BASE_WEIGHT_LBS":35,"WEIGHT_MOD":"1","AGE_LEB":150,"AGE_ADULT":20},
{"d96":47,"RACE":"Halfling (Ghostwise)","BASE_HEIGHT_IN":31,"HEIGHT_MOD":"2d4","BASE_WEIGHT_LBS":35,"WEIGHT_MOD":"1","AGE_LEB":150,"AGE_ADULT":20},
{"d96":48,"RACE":"Halfling (Lightfoot)","BASE_HEIGHT_IN":31,"HEIGHT_MOD":"2d4","BASE_WEIGHT_LBS":35,"WEIGHT_MOD":"1","AGE_LEB":150,"AGE_ADULT":20},
{"d96":49,"RACE":"Halfling (Lotusden)","BASE_HEIGHT_IN":31,"HEIGHT_MOD":"2d4","BASE_WEIGHT_LBS":35,"WEIGHT_MOD":"1","AGE_LEB":150,"AGE_ADULT":20},
{"d96":50,"RACE":"Halfling (Mark of Healing)","BASE_HEIGHT_IN":31,"HEIGHT_MOD":"2d4","BASE_WEIGHT_LBS":35,"WEIGHT_MOD":"1","AGE_LEB":150,"AGE_ADULT":20},
{"d96":51,"RACE":"Halfling (Mark of Hospitality)","BASE_HEIGHT_IN":31,"HEIGHT_MOD":"2d4","BASE_WEIGHT_LBS":35,"WEIGHT_MOD":"1","AGE_LEB":150,"AGE_ADULT":20},
{"d96":52,"RACE":"Halfling (Stout)","BASE_HEIGHT_IN":31,"HEIGHT_MOD":"2d4","BASE_WEIGHT_LBS":35,"WEIGHT_MOD":"1","AGE_LEB":150,"AGE_ADULT":20},
{"d96":53,"RACE":"Hobgoblin","BASE_HEIGHT_IN":56,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":100,"AGE_ADULT":25},
{"d96":54,"RACE":"Human","BASE_HEIGHT_IN":56,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":100,"AGE_ADULT":25},
{"d96":55,"RACE":"Human (Mark of Finding)","BASE_HEIGHT_IN":56,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":100,"AGE_ADULT":25},
{"d96":56,"RACE":"Human (Mark of Handling)","BASE_HEIGHT_IN":56,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":100,"AGE_ADULT":25},
{"d96":57,"RACE":"Human (Mark of Making)","BASE_HEIGHT_IN":56,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":100,"AGE_ADULT":25},
{"d96":58,"RACE":"Human (Mark of Passage)","BASE_HEIGHT_IN":56,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":100,"AGE_ADULT":25},
{"d96":59,"RACE":"Human (Mark of Sentinel)","BASE_HEIGHT_IN":56,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":100,"AGE_ADULT":25},
{"d96":60,"RACE":"Human (Variant)","BASE_HEIGHT_IN":56,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":100,"AGE_ADULT":25},
{"d96":61,"RACE":"Kalashtar","BASE_HEIGHT_IN":56,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":100,"AGE_ADULT":25},
{"d96":62,"RACE":"Kenku","BASE_HEIGHT_IN":52,"HEIGHT_MOD":"2d8","BASE_WEIGHT_LBS":50,"WEIGHT_MOD":"1d6","AGE_LEB":60,"AGE_ADULT":12},
{"d96":63,"RACE":"Kobold","BASE_HEIGHT_IN":25,"HEIGHT_MOD":"2d4","BASE_WEIGHT_LBS":25,"WEIGHT_MOD":"1","AGE_LEB":120,"AGE_ADULT":6},
{"d96":64,"RACE":"Leonin","BASE_HEIGHT_IN":66,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":180,"WEIGHT_MOD":"2d6","AGE_LEB":100,"AGE_ADULT":25},
{"d96":65,"RACE":"Lizardfolk","BASE_HEIGHT_IN":57,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":120,"WEIGHT_MOD":"2d6","AGE_LEB":14,"AGE_ADULT":60},
{"d96":66,"RACE":"Loxodon","BASE_HEIGHT_IN":79,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":295,"WEIGHT_MOD":"2d4","AGE_LEB":450,"AGE_ADULT":25},
{"d96":67,"RACE":"Minotaur","BASE_HEIGHT_IN":64,"HEIGHT_MOD":"2d8","BASE_WEIGHT_LBS":175,"WEIGHT_MOD":"2d6","AGE_LEB":150,"AGE_ADULT":17},
{"d96":68,"RACE":"Orc","BASE_HEIGHT_IN":64,"HEIGHT_MOD":"2d8","BASE_WEIGHT_LBS":175,"WEIGHT_MOD":"2d6","AGE_LEB":80,"AGE_ADULT":16},
{"d96":69,"RACE":"Satyr","BASE_HEIGHT_IN":56,"HEIGHT_MOD":"2d8","BASE_WEIGHT_LBS":100,"WEIGHT_MOD":"2d4","AGE_LEB":100,"AGE_ADULT":25},
{"d96":70,"RACE":"Shifter (Beasthide)","BASE_HEIGHT_IN":56,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":70,"AGE_ADULT":10},
{"d96":71,"RACE":"Shifter (Longtooth)","BASE_HEIGHT_IN":56,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":70,"AGE_ADULT":10},
{"d96":72,"RACE":"Shifter (Swiftstride)","BASE_HEIGHT_IN":56,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":70,"AGE_ADULT":10},
{"d96":73,"RACE":"Shifter (Wildhunt)","BASE_HEIGHT_IN":56,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":70,"AGE_ADULT":10},
{"d96":74,"RACE":"Simic Hybrid (Human)","BASE_HEIGHT_IN":56,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":90,"AGE_ADULT":25},
{"d96":75,"RACE":"Simic Hybrid (Elf)","BASE_HEIGHT_IN":56,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":675,"AGE_ADULT":25},
{"d96":76,"RACE":"Simic Hybrid (Vedalken)","BASE_HEIGHT_IN":56,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":300,"AGE_ADULT":40},
{"d96":77,"RACE":"Tabaxi","BASE_HEIGHT_IN":58,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":90,"WEIGHT_MOD":"2d4","AGE_LEB":100,"AGE_ADULT":25},
{"d96":78,"RACE":"Tiefling (Asmodeus)","BASE_HEIGHT_IN":57,"HEIGHT_MOD":"2d8","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":110,"AGE_ADULT":25},
{"d96":79,"RACE":"Tiefling (Baalzebul)","BASE_HEIGHT_IN":57,"HEIGHT_MOD":"2d8","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":110,"AGE_ADULT":25},
{"d96":80,"RACE":"Tiefling (Base)","BASE_HEIGHT_IN":57,"HEIGHT_MOD":"2d8","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":110,"AGE_ADULT":25},
{"d96":81,"RACE":"Tiefling (Dispater)","BASE_HEIGHT_IN":57,"HEIGHT_MOD":"2d8","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":110,"AGE_ADULT":25},
{"d96":82,"RACE":"Tiefling (Fierna)","BASE_HEIGHT_IN":57,"HEIGHT_MOD":"2d8","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":110,"AGE_ADULT":25},
{"d96":83,"RACE":"Tiefling (Glasya)","BASE_HEIGHT_IN":57,"HEIGHT_MOD":"2d8","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":110,"AGE_ADULT":25},
{"d96":84,"RACE":"Tiefling (Levistus)","BASE_HEIGHT_IN":57,"HEIGHT_MOD":"2d8","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":110,"AGE_ADULT":25},
{"d96":85,"RACE":"Tiefling (Mammon)","BASE_HEIGHT_IN":57,"HEIGHT_MOD":"2d8","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":110,"AGE_ADULT":25},
{"d96":86,"RACE":"Tiefling (Mephistopheles)","BASE_HEIGHT_IN":57,"HEIGHT_MOD":"2d8","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":110,"AGE_ADULT":25},
{"d96":87,"RACE":"Tiefling (Devil's Tongue)","BASE_HEIGHT_IN":57,"HEIGHT_MOD":"2d8","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":110,"AGE_ADULT":25},
{"d96":88,"RACE":"Tiefling (Hellfire)","BASE_HEIGHT_IN":57,"HEIGHT_MOD":"2d8","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":110,"AGE_ADULT":25},
{"d96":89,"RACE":"Tiefling (Infernal Legacy)","BASE_HEIGHT_IN":57,"HEIGHT_MOD":"2d8","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":110,"AGE_ADULT":25},
{"d96":90,"RACE":"Tiefling (Winged)","BASE_HEIGHT_IN":57,"HEIGHT_MOD":"2d8","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":110,"AGE_ADULT":25},
{"d96":91,"RACE":"Tiefling (Zariel)","BASE_HEIGHT_IN":57,"HEIGHT_MOD":"2d8","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":110,"AGE_ADULT":25},
{"d96":92,"RACE":"Triton","BASE_HEIGHT_IN":54,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":90,"WEIGHT_MOD":"2d4","AGE_LEB":200,"AGE_ADULT":15},
{"d96":93,"RACE":"Vedalken","BASE_HEIGHT_IN":64,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":350,"AGE_ADULT":40},
{"d96":94,"RACE":"Verdan","BASE_HEIGHT_IN":56,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":200,"AGE_ADULT":24},
{"d96":95,"RACE":"Warforged","BASE_HEIGHT_IN":70,"HEIGHT_MOD":"2d6","BASE_WEIGHT_LBS":270,"WEIGHT_MOD":"4","AGE_LEB":1000,"AGE_ADULT":1},
{"d96":96,"RACE":"Yuan-ti Pureblood","BASE_HEIGHT_IN":56,"HEIGHT_MOD":"2d10","BASE_WEIGHT_LBS":110,"WEIGHT_MOD":"2d4","AGE_LEB":100,"AGE_ADULT":25}]

let tableNPCAge_total = [{"d1000000":926954,"LEB_PERCENT":0.0625},
{"d1000000":848908,"LEB_PERCENT":0.125},
{"d1000000":770863,"LEB_PERCENT":0.1875},
{"d1000000":693817,"LEB_PERCENT":0.25},
{"d1000000":621771,"LEB_PERCENT":0.3125},
{"d1000000":545725,"LEB_PERCENT":0.375},
{"d1000000":469679,"LEB_PERCENT":0.4375},
{"d1000000":384633,"LEB_PERCENT":0.5},
{"d1000000":299588,"LEB_PERCENT":0.5625},
{"d1000000":287842,"LEB_PERCENT":0.625},
{"d1000000":276096,"LEB_PERCENT":0.6875},
{"d1000000":223050,"LEB_PERCENT":0.75},
{"d1000000":180004,"LEB_PERCENT":0.8125},
{"d1000000":142458,"LEB_PERCENT":0.875},
{"d1000000":104913,"LEB_PERCENT":0.9375},
{"d1000000":77867,"LEB_PERCENT":1},
{"d1000000":50821,"LEB_PERCENT":1.0625},
{"d1000000":37775,"LEB_PERCENT":1.125},
{"d1000000":30729,"LEB_PERCENT":1.1875},
{"d1000000":24683,"LEB_PERCENT":1.25},
{"d1000000":17238,"LEB_PERCENT":1.3125},
{"d1000000":10992,"LEB_PERCENT":1.375},
{"d1000000":5346,"LEB_PERCENT":1.4375},
{"d1000000":1,"LEB_PERCENT":1.5}]

let tableNPCRelationshipOrientationRealWorld = [{"d10001":"501-10001","RELATIONSHIP_ORIENTATION":"monoamorous"},
{"d10001":"1-500","RELATIONSHIP_ORIENTATION":"polyamorous"}]

let tableNPCSexualOrientationRealWorld = [{"d10001":"651-10001","SEXUAL_ORIENTATION":"heterosexual"},
{"d10001":"481-650","SEXUAL_ORIENTATION":"homosexual"},
{"d10001":"301-480","SEXUAL_ORIENTATION":"bisexual"},
{"d10001":"201-300","SEXUAL_ORIENTATION":"pansexual"},
{"d10001":"101-200","SEXUAL_ORIENTATION":"asexual"},
{"d10001":"1-100","SEXUAL_ORIENTATION":"sapiosexual"}]

let tableNPCGenderRealWorld = [{"d10001":"201-10001","GENDER":"cisgender"},
{"d10001":"181-200","GENDER":"non-binary"},
{"d10001":"123-180","GENDER":"transgender"},
{"d10001":"62.-122","GENDER":"agender"},
{"d10001":"1-61","GENDER":"genderfluid"}]

let tableNPCSexRealWorld = [{"d10001":"5186-10001","SEX":"male"},
{"d10001":"171-5185","SEX":"female"},
{"d10001":"1-1770","SEX":"intersex"}]

let tableNPCPersonality = [{"d16":1,"NAME":"Architect","TYPE":"INTJ-A / INTJ-T","DESCRIPTION":"Imaginative and strategic thinkers, with a plan for everything."},
{"d16":2,"NAME":"Logician","TYPE":"INTP-A / INTP-T","DESCRIPTION":"Innovative inventors with an unquenchable thirst for knowledge."},
{"d16":3,"NAME":"Commander","TYPE":"ENTJ-A / ENTJ-T","DESCRIPTION":"Bold, imaginative and strong-willed leaders, always finding a way – or making one."},
{"d16":4,"NAME":"Debater","TYPE":"ENTP-A / ENTP-T","DESCRIPTION":"Smart and curious thinkers who cannot resist an intellectual challenge."},
{"d16":5,"NAME":"Advocate","TYPE":"INFJ-A / INFJ-T","DESCRIPTION":"Quiet and mystical, yet very inspiring and tireless idealists."},
{"d16":6,"NAME":"Mediator","TYPE":"INFP-A / INFP-T","DESCRIPTION":"Poetic, kind and altruistic people, always eager to help a good cause."},
{"d16":7,"NAME":"Protagonist","TYPE":"ENFJ-A / ENFJ-T","DESCRIPTION":"Charismatic and inspiring leaders, able to mesmerize their listeners."},
{"d16":8,"NAME":"Campaigner","TYPE":"ENFP-A / ENFP-T","DESCRIPTION":"Enthusiastic, creative and sociable free spirits, who can always find a reason to smile."},
{"d16":9,"NAME":"Logistician","TYPE":"ISTJ-A / ISTJ-T","DESCRIPTION":"Practical and fact-minded individuals, whose reliability cannot be doubted."},
{"d16":10,"NAME":"Defender","TYPE":"ISFJ-A / ISFJ-T","DESCRIPTION":"Very dedicated and warm protectors, always ready to defend their loved ones."},
{"d16":11,"NAME":"Executive","TYPE":"ESTJ-A / ESTJ-T","DESCRIPTION":"Excellent administrators, unsurpassed at managing things – or people."},
{"d16":12,"NAME":"Consul","TYPE":"ESFJ-A / ESFJ-T","DESCRIPTION":"Extraordinarily caring, social and popular people, always eager to help."},
{"d16":13,"NAME":"Virtuoso","TYPE":"ISTP-A / ISTP-T","DESCRIPTION":"Bold and practical experimenters, masters of all kinds of tools."},
{"d16":14,"NAME":"Adventurer","TYPE":"ISFP-A / ISFP-T","DESCRIPTION":"Flexible and charming artists, always ready to explore and experience something new."},
{"d16":15,"NAME":"Entrepreneur","TYPE":"ESTP-A / ESTP-T","DESCRIPTION":"Smart, energetic and very perceptive people, who truly enjoy living on the edge."},
{"d16":16,"NAME":"Entertainer","TYPE":"ESFP-A / ESFP-T","DESCRIPTION":"Spontaneous, energetic and enthusiastic people – life is never boring around them."}]

let tableNPCVoiceQuirk = [{"d99":1,"QUIRK":"Snorts every now and then"},
{"d99":2,"QUIRK":"Typical High pitched granny"},
{"d99":3,"QUIRK":"Sound of cleaning teeth with tongue"},
{"d99":4,"QUIRK":"British posh ( potato in the mouth style)"},
{"d99":5,"QUIRK":"Nasaled"},
{"d99":6,"QUIRK":"A wording crouch, ya see, ya see!!!"},
{"d99":7,"QUIRK":"St...st...stutter"},
{"d99":8,"QUIRK":"Creepy repetition of the last word word"},
{"d99":9,"QUIRK":"Yoda speak they do"},
{"d99":10,"QUIRK":"super whisper all the time"},
{"d99":11,"QUIRK":"LOUD AND BOISTEROUS LAUGHING SOMETIMES AS WELL"},
{"d99":12,"QUIRK":"Pausing at times....that don’t work (the Christopher Walken approach)"},
{"d99":13,"QUIRK":"Pausing... at ...times... that really...don’t work... (William Shatner approach)"},
{"d99":14,"QUIRK":"Lisping"},
{"d99":15,"QUIRK":"Always repeating the last two words of the previous speaker"},
{"d99":16,"QUIRK":"Awkward timing for burping (additional skill recommended)"},
{"d99":17,"QUIRK":"Ending every speaking part with a sidetracking question"},
{"d99":18,"QUIRK":"Replies with a single word whenever possible."},
{"d99":19,"QUIRK":"Monotone, even when happy or furious."},
{"d99":20,"QUIRK":"They stop after every sentence, never really telegraphing when they are finished talking"},
{"d99":21,"QUIRK":"Nervous: speaks quickly, eyes darting around, often licks lips"},
{"d99":22,"QUIRK":"Speaks like an AC-TOR: overexaggerate all the mouth motions and project clearly."},
{"d99":23,"QUIRK":"Pick a syllable: every time they say that syllable, it gets lengthened or shortened unnaturally"},
{"d99":24,"QUIRK":"Clearly a snake: lengthens all their sssssses."},
{"d99":25,"QUIRK":"Smacks and purses lips at odd point in the sentence"},
{"d99":26,"QUIRK":"Runs sentences together, then takes breaths a few words after the start of the next sentence"},
{"d99":27,"QUIRK":"Only speaks out of the corner of their mouth - keep one side of your lips pressed together while speaking"},
{"d99":28,"QUIRK":"Speaks through clenched teeth"},
{"d99":29,"QUIRK":"Has a severe underbite or overbite - push your lower jaw forward or backward while speaking"},
{"d99":30,"QUIRK":"Pull your tongue back so that it hits the middle of your palate instead of the front while pronouncing ts, ns, rs etc"},
{"d99":31,"QUIRK":"Attempt to speak with your mouth as closed as possible, almost without moving your lips"},
{"d99":32,"QUIRK":"Pull the corners of your mouth back, like a fake smile"},
{"d99":33,"QUIRK":"Replace all vowels with the same vowel. This can get close to a parody accent, so try it out before bringing it to the table!"},
{"d99":34,"QUIRK":"Speaks with the tip of the tongue pushed out between the teeth."},
{"d99":35,"QUIRK":"Instead of saying 'uh' or 'um', use another syllable or word. A wizard might use 'hmm', an orc might growl, etc"},
{"d99":36,"QUIRK":"Never finishes a sentence without going off on tangents and switching trains of thought"},
{"d99":37,"QUIRK":"Every sentence is a question"},
{"d99":38,"QUIRK":"Wildly VARYING! intonation? andspeedof wooorrrddds."},
{"d99":39,"QUIRK":"Lots of extraneous words, yeah, but, y'see, the thing is... like I said, lots of extraneous words. Words. See?"},
{"d99":40,"QUIRK":"Never uses articles such as 'a' or 'the'"},
{"d99":41,"QUIRK":"Every wonderful word has extra dewy soft adjectives"},
{"d99":42,"QUIRK":"Says UWU in replace of important words"},
{"d99":43,"QUIRK":"stopping talking for a moment to see something that catched his eye (a butterfly etc)"},
{"d99":44,"QUIRK":"Whispering "},
{"d99":45,"QUIRK":"Demure and soft spoken when addressing a group and loud with bulging eyes when addressing a single individual"},
{"d99":46,"QUIRK":"Eyes darting back and forth from people and innanimate objects after only a few words and licking their lips only when speaking to one chosen individual or object."},
{"d99":47,"QUIRK":"Using a puppet"},
{"d99":48,"QUIRK":"Is always taking their jacket (or some article of clothing) off and putting it back on."},
{"d99":49,"QUIRK":"A voice that is barely containing from bursting out in song."},
{"d99":50,"QUIRK":"A deep and stern voice that gets super high when triggered by....something?"},
{"d99":51,"QUIRK":"Every conversation starts with a one word sentence. Their next sentence has two. The next 3. Then 4. And on and on. This pattern resets when the subject is changed or possibly when they reach a certain sentence length. (Might make this a curse that ends/transfers when someone copies the pattern with them for a few sentences)"},
{"d99":52,"QUIRK":"They drink after almost every sentence."},
{"d99":53,"QUIRK":"99% of this persons speech is swearing."},
{"d99":54,"QUIRK":"Morose: Depressed. Think of Eeyore (sigh a lot, look down and shake your head)."},
{"d99":55,"QUIRK":"Paranoid: Look over your shoulder often, say 'shh...' and listen sideways."},
{"d99":56,"QUIRK":"Tongue-tied: (talk with your tongue thtuck to your fwont teef) but be very serious, not silly. "},
{"d99":57,"QUIRK":"Distracted: Look off to the side, say "},
{"d99":58,"QUIRK":"Itchy: Don't describe it, don't even mention it aloud, just dramatically scratch various places as you talk."},
{"d99":59,"QUIRK":"Half deaf: Speak loud and ask 'what?' often, or better yet, speak extra softly."},
{"d99":60,"QUIRK":"Mute: Uses only hand gestures."},
{"d99":61,"QUIRK":"Blind: Put your hands on their face as they speak. If you start laughing, you'll lose them. Remember, try to be very serious."},
{"d99":62,"QUIRK":"Common as second language: Use a strange dialect. Click your tongue every other word and start (or end) every word with 'ssss'. "},
{"d99":63,"QUIRK":"Dizzy: Sway from side to side as you listen but not when you speak."},
{"d99":64,"QUIRK":"Close Talker : has no sense of a personal bubble."},
{"d99":65,"QUIRK":"Short Stopper : they never finish their senten"},
{"d99":66,"QUIRK":"Curser : every other word is profanity. But in a different language. "},
{"d99":67,"QUIRK":"Phlegmy : keeps grossly clearing their throat. Khhhhuuuuuuuggggrrrhhhh. Kuh. Kuuuuuuuugggghhhhhrhhh."},
{"d99":68,"QUIRK":"Bad teeth : covers their mouth when they speak"},
{"d99":69,"QUIRK":"Breathy : "},
{"d99":70,"QUIRK":"Speak without separating your teeth"},
{"d99":71,"QUIRK":"Keeps saying random stuff until BA tells them to shut up. "},
{"d99":72,"QUIRK":"Uses “the” in every sentence. I wrote an essay that way and it was pretty fun"},
{"d99":73,"QUIRK":"Slightly sniffly"},
{"d99":74,"QUIRK":"Tap your foot on the ground/ hands on the table constantly"},
{"d99":75,"QUIRK":"Curl your tongue up into the roof of your mouth"},
{"d99":76,"QUIRK":"Add underhanded/sarcastic comments in whispers during conversation “oh hello! You’re here again! under their breathwooonderful”"},
{"d99":77,"QUIRK":"Laughs after every joke with a single loud HA!"},
{"d99":78,"QUIRK":"Speak with your hands! vigorous hand waving"},
{"d99":79,"QUIRK":"Intermittently clack your teeth together"},
{"d99":80,"QUIRK":"Don’t look at the players when speaking, look at and fidget with your fingers and clothes"},
{"d99":81,"QUIRK":"breathe audibly when not speaking"},
{"d99":82,"QUIRK":"Only uses proper nouns"},
{"d99":83,"QUIRK":"Barks at the end of each sentence"},
{"d99":84,"QUIRK":"Never addresses anyone by the correct name"},
{"d99":85,"QUIRK":"Imitate any characters in the technicolor films Robin Hood or Ivanhoe"},
{"d99":86,"QUIRK":"Become BRIAN BLESSED"},
{"d99":87,"QUIRK":"Constantly looking behind themselves as if they are being watched or expecting someone to find them, thus speaking quickly and trying to rush whatever is being said ie Oh, hey, welcome to (insert city) Wha? looks over shoulder sharply what was that? Hm nothing, alright, sorry what do you need again?Kind of like distracted but more worried and anxious"},
{"d99":88,"QUIRK":"Narcoleptic, as in falls asleep mid sentence and the players must attempt to wake them up somehow"},
{"d99":89,"QUIRK":"Rhymes all the times"},
{"d99":90,"QUIRK":"Over explain everything, even if it's obvious. It's a good and quirky way to add some character to an NPC in role playing games like D&D, that's Dungeons & Dragons in case you were wondering."},
{"d99":91,"QUIRK":"Repeats a key phrase in a whispered tone. ... in a whispered tone"},
{"d99":92,"QUIRK":"Tries to speak in puns. The more pun-ishing, the better."},
{"d99":93,"QUIRK":"repeats every sentence just said but under their breath as they're inhaling to say the next sentence. (my brother and several people I know do this and it drives me up the wall)"},
{"d99":94,"QUIRK":"Constantly referring to people by condescending little nicknames: Chief, Sport, Tiger, Kid, Cat, Skippy, Pal, Killer, Dog, Guy, Boss, Junior, Ace, Champ, Slugger, Bud, Kiddo, Amigo, Bro, Slick, Son, Cap'n, Hoss, Tex, Slim, Doc, Jack, Fella, Cuz...."},
{"d99":95,"QUIRK":"I like slow and methodical with articulation, think Snape from Harry Potter."},
{"d99":96,"QUIRK":"Wizard/similar intellectual: Give the wizard a special lexicon to refer to common terms in their own, intelligent way. For example: instead of Transmutation it's Etheric Chemistry and instead of Illusion it's Mimetic Dimensional Alteration"},
{"d99":97,"QUIRK":"Begins every statement with "},
{"d99":98,"QUIRK":"Pick a letter like "},
{"d99":99,"QUIRK":"clergyman sing song"}]