let wind = [{"roll":1,"result":"no wind"},
{"roll":2,"result":"no wind"},
{"roll":3,"result":"no wind"},
{"roll":4,"result":"no wind"},
{"roll":5,"result":"no wind"},
{"roll":6,"result":"no wind"},
{"roll":7,"result":"no wind"},
{"roll":8,"result":"no wind"},
{"roll":9,"result":"no wind"},
{"roll":10,"result":"no wind"},
{"roll":11,"result":"no wind"},
{"roll":12,"result":"no wind"},
{"roll":13,"result":"light wind"},
{"roll":14,"result":"light wind"},
{"roll":15,"result":"light wind"},
{"roll":16,"result":"light wind"},
{"roll":17,"result":"light wind"},
{"roll":18,"result":"heavy wind"},
{"roll":19,"result":"heavy wind"},
{"roll":20,"result":"heavy wind"}]

let temperature = [{"roll":1,"result":" +1d8"},
{"roll":2,"result":"+1d8"},
{"roll":3,"result":"+1d8"},
{"roll":4,"result":"+1d8"},
{"roll":5,"result":"+1d8"},
{"roll":6,"result":"+1d8"},
{"roll":7,"result":"+1d8"},
{"roll":8,"result":"-1d8"},
{"roll":9,"result":"-1d8"},
{"roll":10,"result":"-1d8"},
{"roll":11,"result":"-1d8"},
{"roll":12,"result":"-1d8"},
{"roll":13,"result":"-1d8"},
{"roll":14,"result":"-1d8"},
{"roll":15,"result":"-1d4*10"},
{"roll":16,"result":"-1d4*10"},
{"roll":17,"result":"-1d4*10"},
{"roll":18,"result":"+1d4*10"},
{"roll":19,"result":"+1d4*10"},
{"roll":20,"result":"+1d4*10"}]

let direction = [{"roll":1,"result":"N"},
{"roll":2,"result":"NNE"},
{"roll":3,"result":"NE"},
{"roll":4,"result":"ENE"},
{"roll":5,"result":"ENE"},
{"roll":6,"result":"ESE"},
{"roll":7,"result":"SE"},
{"roll":8,"result":"SSE"},
{"roll":9,"result":"S"},
{"roll":10,"result":"SSW"},
{"roll":11,"result":"SW"},
{"roll":12,"result":"WSW"},
{"roll":13,"result":"WSW"},
{"roll":14,"result":"WNW"},
{"roll":15,"result":"NW"},
{"roll":16,"result":"NNW"}]

let weather = [{"Type":"Tropical","Spring_Average_Temp_F":88.88,"Spring_Precipitation_Prob":490,"Spring_Heavy_Precipitation_Prob":122.5,"Summer_Average_Temp_F":87.8,"Summer_Precipitation_Prob":440,"Summer_Heavy_Precipitation_Prob":110,"Fall_Average_Temp_F":87.62,"Fall_Precipitation_Prob":540,"Fall_Heavy_Precipitation_Prob":135,"Winter_Average_Temp_F":86.72,"Winter_Precipitation_Prob":500,"Winter_Heavy_Precipitation_Prob":125},
{"Type":"Arid/Dry","Spring_Average_Temp_F":90,"Spring_Precipitation_Prob":40,"Spring_Heavy_Precipitation_Prob":10,"Summer_Average_Temp_F":97,"Summer_Precipitation_Prob":0,"Summer_Heavy_Precipitation_Prob":0,"Fall_Average_Temp_F":87,"Fall_Precipitation_Prob":20,"Fall_Heavy_Precipitation_Prob":5,"Winter_Average_Temp_F":76,"Winter_Precipitation_Prob":100,"Winter_Heavy_Precipitation_Prob":25},
{"Type":"Temperate","Spring_Average_Temp_F":71.24,"Spring_Precipitation_Prob":310,"Spring_Heavy_Precipitation_Prob":77.5,"Summer_Average_Temp_F":91.22,"Summer_Precipitation_Prob":250,"Summer_Heavy_Precipitation_Prob":62.5,"Fall_Average_Temp_F":72.68,"Fall_Precipitation_Prob":250,"Fall_Heavy_Precipitation_Prob":62.5,"Winter_Average_Temp_F":50.18,"Winter_Precipitation_Prob":220,"Winter_Heavy_Precipitation_Prob":55},
{"Type":"Continental","Spring_Average_Temp_F":42.26,"Spring_Precipitation_Prob":200,"Spring_Heavy_Precipitation_Prob":50,"Summer_Average_Temp_F":62.06,"Summer_Precipitation_Prob":440,"Summer_Heavy_Precipitation_Prob":110,"Fall_Average_Temp_F":39.56,"Fall_Precipitation_Prob":190,"Fall_Heavy_Precipitation_Prob":47.5,"Winter_Average_Temp_F":15.98,"Winter_Precipitation_Prob":30,"Winter_Heavy_Precipitation_Prob":7.5},
{"Type":"Polar","Spring_Average_Temp_F":31.1,"Spring_Precipitation_Prob":170,"Spring_Heavy_Precipitation_Prob":42.5,"Summer_Average_Temp_F":59.7,"Summer_Precipitation_Prob":260,"Summer_Heavy_Precipitation_Prob":65,"Fall_Average_Temp_F":23.9,"Fall_Precipitation_Prob":350,"Fall_Heavy_Precipitation_Prob":87.5,"Winter_Average_Temp_F":-4.36,"Winter_Precipitation_Prob":270,"Winter_Heavy_Precipitation_Prob":67.5}]