let wsExtreme = [{"d100":1,"RESULT":"A fireball explodes with you at the center. You and each creature within 20 feet of you who must make a Dexterity saving throw using your spell save DC, taking 5d6 fire damage on a failed save, or half as much damage on a successful one."},
{"d100":2,"RESULT":"You recover all your expended spell slots."},
{"d100":3,"RESULT":"You lose the ability to hear for 1 day."},
{"d100":4,"RESULT":"Each creature within 30 feet of you takes 1d10 necrotic damage. You regain hit points equal to the sum of damage dealt."},
{"d100":5,"RESULT":"You teleport to an alternate plane, then return to the location where you started after 1 minute."},
{"d100":6,"RESULT":"You transform into a large empty barrel for 1 minute, during which time you considered petrified."},
{"d100":7,"RESULT":"You are at the center of a darkness spell for 1 minute."},
{"d100":8,"RESULT":"You are frightened by the nearest creature until the end of your next turn."},
{"d100":9,"RESULT":"You are resistant to all damage types for 1 minute."},
{"d100":10,"RESULT":"A random creature within 60 feet of you is poisoned for 1d4 hours."},
{"d100":11,"RESULT":"Make a Wisdom saving throw against your own spell save DC. If you fail, you are polymorphed into giant dragonfly for 1 minute."},
{"d100":12,"RESULT":"Up to three creatures you choose within 30 feet of you take 4d10 lightning damage."},
{"d100":13,"RESULT":"You immediately gain 20 temporary hit points."},
{"d100":14,"RESULT":"You teleport up to 60 feet to an unoccupied space that you can see."},
{"d100":15,"RESULT":"You are the center of a silence spell for 1 minute."},
{"d100":16,"RESULT":"You are vulnerable to fiends for 1 hour. Such creatures gain advantage on attack rolls made against you."},
{"d100":17,"RESULT":"For the next day, any time you make an ability check, roll 1d6 and subtract the result."},
{"d100":18,"RESULT":"For any spell that requires a saving throw you cast within the next minute, the target gains advantage."},
{"d100":19,"RESULT":"The next single target spell you cast within the next minute must target one additional target."},
{"d100":20,"RESULT":"A demon whose CR is equal to your level appears near you. Make a Charisma saving throw against your spell save DC. If you make it, the demon is subservient, otherwise, it is hostile. The demon, if not banished or defeated, vanishes after 1 day."},
{"d100":21,"RESULT":"For the next minute, every creature within 60 feet of you that hears you speak only hears insults as if you are casting vicious mockery at first level."},
{"d100":22,"RESULT":"For the next day, you have advantage on the next 2d6 rolls you make where you don't already have advantage."},
{"d100":23,"RESULT":"You are protected from Aberrations for 1 day. Such creatures cannot attack you or harm you unless they save a Charisma saving throw against your spell save DC."},
{"d100":24,"RESULT":"For 1 minute, a duplicate of yourself appears in the nearest open space which can take actions independently, and goes on the same Initiative as you. However, any damage it takes as well as any spell slots or sorcery point it uses applies to you as well."},
{"d100":25,"RESULT":"A loud boom emanates from you. All creatures within 15 feet take 2d8 thunder damage and must make a Constitution saving throw against your spell save DC or be deafened for 1 minute."},
{"d100":26,"RESULT":"All creatures within 60 feet of you regain 2d8 hit points."},
{"d100":27,"RESULT":"You transform into a marble statue of yourself for 1 minute, during which time you are considered petrified."},
{"d100":28,"RESULT":"You are immune to disease for 1 week."},
{"d100":29,"RESULT":"You immediately drop to 0 hit points."},
{"d100":30,"RESULT":"Make a Wisdom saving throw against your own spell save DC. If you fail, you are transformed into a raven for 1 minute, as if by a polymorph spell."},
{"d100":31,"RESULT":"You are protected from Beasts for 1 day. Such creatures cannot attack you or harm you unless they save a Charisma saving throw against your spell save DC."},
{"d100":32,"RESULT":"You transform into a stuffed toy resembling yourself for 1 minute, during which time you are considered petrified."},
{"d100":33,"RESULT":"You stand at the center a circular wall of fire with a radius of 15 feet. Any creature in any of the spaces covered by this fire must make a Dexterity saving throw against your spell DC or take 5d8 fire damage. The wall of fire remains for 1 minute."},
{"d100":34,"RESULT":"Choose 1 permanent or triggered effect that has happened to you or somebody else that you’ve received from this chart and remove it, even if it was beneficial."},
{"d100":35,"RESULT":"You are vulnerable to Beasts for 1 hour. Such creatures gain advantage when attacking you."},
{"d100":36,"RESULT":"You permanently lose the ability to smell. This sense can be restored with a spell that removes curses such as remove curse."},
{"d100":37,"RESULT":"You are vulnerable to Celestials for 1 hour. Such creatures gain advantage when attacking you."},
{"d100":38,"RESULT":"Make a Wisdom saving throw against your spell save DC. If you fail, you are transformed into a cat for 1 minute, as if by a {5e|Polymorph}} spell."},
{"d100":39,"RESULT":"You are vulnerable to Plants for 1 hour. Such creatures gain advantage when attacking you."},
{"d100":40,"RESULT":"You gain the service of an arcane eye for 1 hour that does not require concentration."},
{"d100":41,"RESULT":"You are protected from Celestials for 1 day. Such creatures cannot attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC."},
{"d100":42,"RESULT":"You transform into a medium-sized potted plant for 1 minute, during which time you are considered petrified."},
{"d100":43,"RESULT":"3d6 random gems appear near you, worth 50gp each."},
{"d100":44,"RESULT":"All allies within 20 feet of you gain a +2 bonus to attack and damage rolls on any melee weapon attack they make within the next minute."},
{"d100":45,"RESULT":"For 2d6 days, you glow bright yellow. You have disadvantage on Stealth checks and anyone trying to perceive you has advantage on their Perception check."},
{"d100":46,"RESULT":"You stand at the center a circular wall of force with a radius of 15 feet. Any creature in any of the spaces covered by this wall must make a Dexterity saving throw against your spell DC or take 5d8 force damage. The wall remains for 1 minute."},
{"d100":47,"RESULT":"All creatures within 20 feet of you are knocked prone."},
{"d100":48,"RESULT":"You are vulnerable to Aberrations for 1 hour. Such creatures gain advantage when attacking you."},
{"d100":49,"RESULT":"For the next day, you are in the Border Ethereal near the location you were last in."},
{"d100":50,"RESULT":"All allies within 20 feet of you gain a +2 bonus to attack and damage rolls on any ranged weapon attack they make within the next minute."},
{"d100":51,"RESULT":"You are at the center of a 10-foot radius antimagic field that negates all magic equal to or less than your level for 1 hour and does not require concentration."},
{"d100":52,"RESULT":"Make a Wisdom saving throw against your spell save DC. If you fail, you are transformed into a wolf for 1 minute, as if by a polymorph spell."},
{"d100":53,"RESULT":"You are protected from Elementals for one day. Such creatures cannot attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC."},
{"d100":54,"RESULT":"All of your hair permanently falls out. Only a spell such as remove curse can end this effect."},
{"d100":55,"RESULT":"You gain the ability to speak one new language of your choice. However, you lose the ability to speak one language you already know."},
{"d100":56,"RESULT":"A 30-foot cube hypnotic pattern appears with you at the center. All creatures within the pattern must succeed on a Wisdom saving throw or fall asleep for 1 minute or until they take damage."},
{"d100":57,"RESULT":"You permanently forget one cantrip. A spell such as remove curse can restore your memory."},
{"d100":58,"RESULT":"You immediately take 2d10 psychic damage."},
{"d100":59,"RESULT":"You are vulnerable to Undead for 1 hour. Such creatures gain advantage when attacking you."},
{"d100":60,"RESULT":"You transform into an iron statue of yourself for 1 minute, during which time you are considered petrified."},
{"d100":61,"RESULT":"You gain an additional spell slot of your highest level for 1 week."},
{"d100":62,"RESULT":"If you die within the next minute, you come back to life as if by the reincarnate spell."},
{"d100":63,"RESULT":"You permanently gain one spell slot of one level below your highest-level spell slot, but lose one 1st-level spell slot. A spell such as remove curse can end this effect."},
{"d100":64,"RESULT":"All creatures that can perceive you must make a Wisdom saving throw against your spell save DC or be frightened of you."},
{"d100":65,"RESULT":"You are vulnerable to Elementals for 1 hour. Such creatures gain advantage when attacking you."},
{"d100":66,"RESULT":"You are protected from Fey for 1 day. Such ceatures cannot attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC."},
{"d100":67,"RESULT":"You gain the service of an arcane sword that does not require concentration until your next short or long rest."},
{"d100":68,"RESULT":"You permanently gain one cantrip. A spell such as remove curse can end this effect."},
{"d100":69,"RESULT":"All allies within 20 feet of you get gain a -2 penalty on attack and damage rolls for any melee attack they make in the next minute."},
{"d100":70,"RESULT":"All allies within 20 feet of you heal up to 3d8 hit points."},
{"d100":71,"RESULT":"You lose the ability to see for 1 day. During this time, you have the blinded condition."},
{"d100":72,"RESULT":"You gain the service of a phantom steed for 1 week."},
{"d100":73,"RESULT":"Make a Constitution saving throw against your spell save DC. If you fail, you are stunned for 1 minute."},
{"d100":74,"RESULT":"You transform into a stone statue of yourself for 1 minute, during which time you are considered petrified."},
{"d100":75,"RESULT":"All creatures within 20 feet of you, including you, must make a Dexterity save against your spell save DC or be affected by a faerie fire spell."},
{"d100":76,"RESULT":"Permanently increase one ability score of your choice by 1 point. Permanently decrease a different ability score of your choice by 1 point. A spell such as remove curse can end this effect."},
{"d100":77,"RESULT":"You gain proficiency in one tool or weapon type you don’t already have for 1 day."},
{"d100":78,"RESULT":"Make a Wisdom saving throw against your spell save DC. If you fail, you are transformed into a giant spider for 1 minute, as if by the polymorph spell."},
{"d100":79,"RESULT":"Gain the sympathy effects of the antipathy/sympathy spell for 3d6 days."},
{"d100":80,"RESULT":"You are protected from Fiends for one day. Such creatures cannot attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC."},
{"d100":81,"RESULT":"All allies within 20 feet of you gain a -2 penalty to attack and damage rolls for any ranged attack they make within the next minute."},
{"d100":82,"RESULT":"For one minute, any spell with a casting time of 1 action can be cast as a bonus action."},
{"d100":83,"RESULT":"Make a Wisdom saving throw against your spell save DC. If you fail, you are transformed into a giant rabbit for 1 minute, as if by the polymorph"},
{"d100":84,"RESULT":"The next time you cast a spell, do not roll on this chart."},
{"d100":85,"RESULT":"For the next day, you gain proficiency in all skills that you are not already proficient in."},
{"d100":86,"RESULT":"The next time you cast a spell, roll twice on this chart. Both effects will apply."},
{"d100":87,"RESULT":"You are vulnerable to Fey for 1 hour. Such creatures gain advantage when attacking you."},
{"d100":88,"RESULT":"You transform into an empty wooden chest for 1 minute, during which time you are considered petrified."},
{"d100":89,"RESULT":"Gain the antipathy effects of the antipathy/sympathy spell for 3d6 days."},
{"d100":90,"RESULT":"All creatures within 30 feet of you must make a Wisdom saving throw. Any creature immune to magical sleep automatically succeeds on its saving throw. Those that fail fall asleep for 1d6 minutes."},
{"d100":91,"RESULT":"You are protected from Plants for 1 day. Such creatures cannot attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC."},
{"d100":92,"RESULT":"All your allies within 20 feet of you gain a +2 bonus to their AC for 1 minute."},
{"d100":93,"RESULT":"The next time you fall below 0 hit points within the next month, you automatically fail your first death saving throw."},
{"d100":94,"RESULT":"You gain two spell slots at your second-highest level for 1 week."},
{"d100":95,"RESULT":"For the next day, any time you make an ability check, roll 1d6 and add the result."},
{"d100":96,"RESULT":"Make a Wisdom saving throw against your spell save DC. If you fail, you are transformed into a sheep for 1 minute, as if by the polymorph spell."},
{"d100":97,"RESULT":"All allies within 30 feet of you gain a -2 penalty to their AC for 1 minute."},
{"d100":98,"RESULT":"You are protected from Undead for 1 day. Such creatures cannot attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC."},
{"d100":99,"RESULT":"You jump forward in time exactly 1 minute, for 1 minute. From the perspective of everyone else, you cease to exist during that time."},
{"d100":100,"RESULT":"All spells you cast within the next minute automatically fail."}]

let wsModerate = [{"d100":1,"RESULT":"For the next day, your skin tone changes color every 30 minutes, cycling through the colors of the rainbow."},
{"d100":2,"RESULT":"You are confused for 1 minute, as though you were affected by the confusion spell."},
{"d100":3,"RESULT":"Your Strength is increased by 2 for 1 day."},
{"d100":4,"RESULT":"A third eye appears in your forehead, giving you advantage on sight-based Wisdom (Perception) checks for 1 minute."},
{"d100":5,"RESULT":"The next spell you cast within the next minute that does damage, the damage is maximized."},
{"d100":6,"RESULT":"For the next minute, you can teleport up to 20 feet as part of your movement on each of your turns."},
{"d100":7,"RESULT":"You become intoxicated for 2d6 hours."},
{"d100":8,"RESULT":"Your Intelligence is decreased by 2 for 1 day."},
{"d100":9,"RESULT":"Your Wisdom is increased by 2 for 1 day."},
{"d100":10,"RESULT":"For 1 minute, any flammable item you touch, that you aren't already wearing or carrying, bursts into flame."},
{"d100":11,"RESULT":"Plants grow around you and you are restrained for 1 minute."},
{"d100":12,"RESULT":"A random creature within 30 feet of you gains a flying speed equal to its walking speed for 1 minute."},
{"d100":13,"RESULT":"You may immediately take 1 additional action."},
{"d100":14,"RESULT":"If you fall within the next day, you automatically have the benefit of the feather fall spell."},
{"d100":15,"RESULT":"You recover 1 expended spell slot of your choice."},
{"d100":16,"RESULT":"For the next spell you cast within 1 minute that does damage, the damage is minimized."},
{"d100":17,"RESULT":"You have are surrounded by a spectral shield for 1 minute, giving you a +2 bonus to your AC and immunity to magic missile."},
{"d100":18,"RESULT":"You and all creatures within 30 feet of you gain vulnerability to piercing damage for 1 minute."},
{"d100":19,"RESULT":"For 1 minute, you gain resistance to nonmagical bludgeoning, piercing, and slashing damage."},
{"d100":20,"RESULT":"You are protected from Elementals for 1 hour. Such creatures cannot attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC."},
{"d100":21,"RESULT":"For the next minute, one creature of your choice gets a -2 penalty to its AC, attack rolls, and damage rolls."},
{"d100":22,"RESULT":"You and all creatures within 30 feet of you gain vulnerability to bludgeoning damage for 1 minute."},
{"d100":23,"RESULT":"You emanate light in a 30-foot radius for 1 minute. Any creature within 5 feet of you that can see is blinded until the end of its next."},
{"d100":24,"RESULT":"For the next hour, you gain advantage on Charisma checks when dealing with any creature wearing black, but disadvantage if they are wearing white. If they are wearing both, this doesn't apply."},
{"d100":25,"RESULT":"You are protected from Plants for 1 hour. Such creatures cannot attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC."},
{"d100":26,"RESULT":"Your Intelligence is increased by 2 for 1 day."},
{"d100":27,"RESULT":"Within the next hour, you have advantage on the next roll you make where you don't already have advantage."},
{"d100":28,"RESULT":"You gain a +2 bonus to your AC for 1 minute."},
{"d100":29,"RESULT":"For the next minute, you are in the Border Ethereal near the location you were last in."},
{"d100":30,"RESULT":"For the next minute, you gain resistance to thunder and force damage."},
{"d100":31,"RESULT":"An imp appears within 30 feet of you. Make a Charisma saving throw against your spell save DC. If you succeed it, the imp is subservient, otherwise, it is hostile. The imp, if not banished or defeated, vanishes after 1 day."},
{"d100":32,"RESULT":"For the next minute, you gain resistance to fire and cold damage."},
{"d100":33,"RESULT":"For the next hour, you gain advantage on Charisma checks when dealing with any creature wearing red, but disadvantage if they are wearing green. If they are wearing both, this doesn't apply."},
{"d100":34,"RESULT":"You gain the service of an arcane eye for 1 minute that does not require concentration."},
{"d100":35,"RESULT":"You lose the ability to smell for 1 day."},
{"d100":36,"RESULT":"You gain a -2 penalty to your AC for 1 minute."},
{"d100":37,"RESULT":"You and all creatures within 30 feet of you gain vulnerability to necrotic damage for 1 minute."},
{"d100":38,"RESULT":"You become invisible and silent for 1 minute."},
{"d100":39,"RESULT":"Your Dexterity is increased by 2 for 1 day."},
{"d100":40,"RESULT":"You can detect the thoughts of 1 creature you can see within 30 feet of you for 1 minute."},
{"d100":41,"RESULT":"For the next minute, all melee attacks you make with a non-magical weapon gain a +1 bonus to hit and to damage, and are considered magical for the purpose of overcoming resistances."},
{"d100":42,"RESULT":"Your Strength is decreased by 2 for 1 hour."},
{"d100":43,"RESULT":"You gain freedom of movement for 1 day."},
{"d100":44,"RESULT":"Your Dexterity is decreased by 2 for 1 hour."},
{"d100":45,"RESULT":"You are affected by a faerie fire spell for 1 minute. You automatically fail the saving throw."},
{"d100":46,"RESULT":"You are protected from Beasts for 1 hour. Such creatures cannot attack you or harm you unless they succeed a Charisma saving throw against your spell save DC."},
{"d100":47,"RESULT":"3d6 gold pieces appear near you."},
{"d100":48,"RESULT":"For 2d6 hours, you have a faint pink glow. Anyone trying to perceive you has advantage on their Perception check."},
{"d100":49,"RESULT":"You gain the ability to breath water for 1 day."},
{"d100":50,"RESULT":"You and all creatures within 30 feet of you gain vulnerability to slashing damage for 1 minute."},
{"d100":51,"RESULT":"For the next minute, light and darkness quickly alternate around you in a 30-foot radius, creating a strobe effect. Sight-based creatures gain a -1 penalty on attack rolls against you and Perception checks against you, and you gain a +1 bonus to Stealth checks."},
{"d100":52,"RESULT":"All creatures within 20 feet of you must make a Strength saving throw against your spell save DC or be knocked prone."},
{"d100":53,"RESULT":"You are protected from Undead for one hour. Such creatures cannot attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC."},
{"d100":54,"RESULT":"For the next minute, you can pass through any solid, non-magical wall that is 6 or fewer inches thick."},
{"d100":55,"RESULT":"You are protected from Fiends for one hour. Such creatures cannot attack you or harm you unless they succeed on a Charisma save against your spell save DC."},
{"d100":56,"RESULT":"You permanently gain one 1st-level spell slot but forget one cantrip that you already know. A spell such as remove curse can end this effect."},
{"d100":57,"RESULT":"You immediately gain 15 temporary hit points."},
{"d100":58,"RESULT":"All gold you are carrying is now silver."},
{"d100":59,"RESULT":"For the next minute, you gain resistance to necrotic and radiant damage."},
{"d100":60,"RESULT":"You are at the center of a fog cloud spell which lasts for 1 minute."},
{"d100":61,"RESULT":"Your Charisma is increased by 2 for 1 day."},
{"d100":62,"RESULT":"You and all creatures within 30 feet of you gain vulnerability to lightning damage for 1 minute."},
{"d100":63,"RESULT":"You and all creatures within 30 feet of you gain vulnerability to force damage for 1 minute."},
{"d100":64,"RESULT":"For the next minute, any creature you touch takes 2d6 lightning damage."},
{"d100":65,"RESULT":"You gain blindsight with a radius of 60 feet for 1 minute."},
{"d100":66,"RESULT":"You are surrounded by a horrible, noxious odor for 1 minute. Anyone within 10 feet of you must make a Constitution saving throw or be stunned."},
{"d100":67,"RESULT":"Your Charisma is decreased by 2 for 1 hour."},
{"d100":68,"RESULT":"You gain the service of a phantom steed for 1 day."},
{"d100":69,"RESULT":"You and all creatures within 30 feet of you gain vulnerability to acid damage for 1 minute."},
{"d100":70,"RESULT":"Your Wisdom is decreased by 2 for 1 hour."},
{"d100":71,"RESULT":"Your speed is increased by 10 feet for 1 day."},
{"d100":72,"RESULT":"You gain the ability to walk on water for 1 day."},
{"d100":73,"RESULT":"You and all creatures within 30 feet of you gain vulnerability to psychic damage for 1 minute."},
{"d100":74,"RESULT":"One creature of your choice gets a +2 bonus to all attack rolls, damage rolls, and their armor class AC for 1 minute."},
{"d100":75,"RESULT":"You lose proficiency in one randomly chosen skill, tool, or weapon type for 2d6 days."},
{"d100":76,"RESULT":"All food and drink within 30 feet of you becomes putrid, spoiled, or rotten. Consuming this food deals 2d6 poison damage and causes the poisoned condition for 1 hour."},
{"d100":77,"RESULT":"All silver you are carrying is now copper."},
{"d100":78,"RESULT":"You and all creatures within 30 feet of you gain vulnerability to fire damage for 1 minute."},
{"d100":79,"RESULT":"You lose proficiency in all skill rolls for 1d4 hours."},
{"d100":80,"RESULT":"You are protected from Fey for one hour. Such creatures cannot attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC."},
{"d100":81,"RESULT":"For the next hour, any time you make an ability check, roll 1d6 and subtract the result."},
{"d100":82,"RESULT":"For the next minute, you gain resistance to poison and psychic damage."},
{"d100":83,"RESULT":"You’re feeling lucky. For the next hour, any time you make an ability check, roll 1d6 and add the result."},
{"d100":84,"RESULT":"You immediately take 2d6 psychic damage."},
{"d100":85,"RESULT":"You gain proficiency in one skill of your choice that you're not already proficient in for one hour."},
{"d100":86,"RESULT":"Your Constitution is increased by 2 for 1 day."},
{"d100":87,"RESULT":"You and all creatures within 30 feet of you gain vulnerability to thunder damage for 1 minute."},
{"d100":88,"RESULT":"You and all creatures within 30 feet of you gain vulnerability to cold damage for 1 minute."},
{"d100":89,"RESULT":"You gain the ability to speak one language of your choice for 1 day."},
{"d100":90,"RESULT":"You and all creatures within 30 feet of you gain vulnerability to radiant damage for 1 minute."},
{"d100":91,"RESULT":"You are protected from Celestials for 1 hour. Such creatures cannot attack you or harm you unless they succeed a on a Charisma saving throw against your spell save DC."},
{"d100":92,"RESULT":"For the next minute, you are unable to cast any spell that causes damage of any type."},
{"d100":93,"RESULT":"You gain spider climb for 1 minute, and it does not require concentration to maintain."},
{"d100":94,"RESULT":"You immediately lose all unspent sorcery points and may not regain them until you have finished a long rest."},
{"d100":95,"RESULT":"You and all creatures within 30 feet of you gain vulnerability to poison damage for 1 minute."},
{"d100":96,"RESULT":"You gain the ability to speak with animals for 1 day."},
{"d100":97,"RESULT":"All food and drink within 30 feet of you is purified."},
{"d100":98,"RESULT":"You are protected from Aberrations for 1 hour. Such creatures cannot attack you or harm you unless they succeed on a Charisma savinng throw against your spell save DC."},
{"d100":99,"RESULT":"All your clothing and equipment teleports to the nearest open space at least 15 feet from you that you can see."},
{"d100":100,"RESULT":"Your Constitution is decreased by 2 for 1 hour."}]

let wsNuisance = [{"d100":1,"RESULT":"A puddle of grease appears where you are standing, with a 10-foot radius. You and anyone within 10 feet of you must make a Dexterity check at your spell save DC or fall prone."},
{"d100":2,"RESULT":"You levitate 6 inches off the ground for 1 minute."},
{"d100":3,"RESULT":"You gain tremorsense with a range of 30 feet for 1 minute."},
{"d100":4,"RESULT":"You make no sounds for 1 minute and you gain advantage on any Dexterity (Stealth) checks."},
{"d100":5,"RESULT":"You grow a beard made of feathers, which remains until you sneeze."},
{"d100":6,"RESULT":"You can't speak for 1 minute. When you try, pink bubbles float out of your mouth."},
{"d100":7,"RESULT":"You are immune to intoxication for the next 5d6 days."},
{"d100":8,"RESULT":"You recover your lowest-level expended spell slot."},
{"d100":9,"RESULT":"For the next minute, you must shout when you speak."},
{"d100":10,"RESULT":"Illusory butterflies and flower petals flutter in the air around you in a 10-foot radius for 1 minute."},
{"d100":11,"RESULT":"You cast mirror image on yourself, which lasts for 1 minute and does not require concentration."},
{"d100":12,"RESULT":"You are surrounded by faint, ethereal music for 1 minute."},
{"d100":13,"RESULT":"You regain all expended sorcery points."},
{"d100":14,"RESULT":"Your hair grows to double its current length over the next minute."},
{"d100":15,"RESULT":"Your hair falls out but grows back within 1 day."},
{"d100":16,"RESULT":"You gain the ability to speak one additional language of your choice for 1 hour."},
{"d100":17,"RESULT":"You are invisible for 1 minute."},
{"d100":18,"RESULT":"Your eyes permanently change color. If they are a blue or grey shade, they turn dark brown, or vice versa. A spell such as remove curse can end this effect."},
{"d100":19,"RESULT":"Small birds flutter and chirp in your vicinity for 1 minute, during which time you automatically fail any Stealth check."},
{"d100":20,"RESULT":"You feel the incredible urge to relieve yourself. Until you do, your Strength and Intelligence are reduced by 1. If you don't relieve yourself in the next 2 minutes, the above effects are removed, but your Charisma score is reduced by 4 for 1 hour or until you change your trousers."},
{"d100":21,"RESULT":"Gnats buzz around your head for 1 minute, distracting you. You must make a Constitution saving throw against your own spell save DC to cast any spell."},
{"d100":22,"RESULT":"You are surrounded by a faint, offensive odor for 1 minute. You gain disadvantage on all Charisma checks."},
{"d100":23,"RESULT":"For the next minute, all spells with a casting time of 1 action or 1 bonus action require 2 consecutive actions to cast."},
{"d100":24,"RESULT":"You have the irresistible urge to scratch an itch in the middle your back, just out of reach, for 1 minute. If you don't scratch it using a back scratcher or some similar device , you must succeed a Constitution saving throw against your spell save DC to cast a spell."},
{"d100":25,"RESULT":"You have a momentary vision of your own death. If you fail a Wisdom saving roll at your spell DC, you are frightened for 1 minute."},
{"d100":26,"RESULT":"Your Charisma is increased by 2 for 1 minute."},
{"d100":27,"RESULT":"Over the next minute, all plants within 20 feet of you grow as if affected by the plant growth spell when cast as an action."},
{"d100":28,"RESULT":"Your eyes glow red for 1 minute."},
{"d100":29,"RESULT":"Your Constitution is increased by 2 for 1 minute."},
{"d100":30,"RESULT":"You add your proficiency bonus to all Charisma checks for the next hour, if you don't already add it."},
{"d100":31,"RESULT":"Your spell components seem to have been rearranged. During the next hour, you must make an Intelligence check against your spell save DC to cast any spell that requires a material component."},
{"d100":32,"RESULT":"For the next minute, you have advantage on the next roll you make where you don't already have advantage."},
{"d100":33,"RESULT":"Every creature within 15 feet of you takes 1 necrotic damage. If you are wounded, you regain hit points up to the amount of damage dealt. If you are not wounded, you gain this amount of temporary hit points."},
{"d100":34,"RESULT":"A magic mouth appears on a nearby wall or flat surface. When you speak, your voice comes from the magic mouth. This lasts for 1 minute."},
{"d100":35,"RESULT":"You can hear exceptionally well for 1 minute, gaining advantage for all Perception checks related to sound."},
{"d100":36,"RESULT":"You lose the ability to smell for 1 hour."},
{"d100":37,"RESULT":"For the next day, each time you say a word with the "},
{"d100":38,"RESULT":"A gentle gust of wind blows outward from you. All creatures within 40 feet of you can feel it, but it otherwise does nothing."},
{"d100":39,"RESULT":"Your Dexterity is increased by 2 for 1 minute."},
{"d100":40,"RESULT":"You immediately take 1d10 radiant damage."},
{"d100":41,"RESULT":"One randomly-chosen non-magical item in your possession that weighs 1 pound or less vanishes and is forever gone."},
{"d100":42,"RESULT":"Your Wisdom is increased by 2 for 1 minute."},
{"d100":43,"RESULT":"You immediately gain 10 temporary hit points."},
{"d100":44,"RESULT":"3d6 silver pieces appear near you."},
{"d100":45,"RESULT":"You regain 5 hit points per round for 1 minute."},
{"d100":46,"RESULT":"An imp appears near you. Make a Charisma saving throw against your spell save DC. If you succeed, the imp is subservient, otherwise, it is hostile. The imp, if not banished or defeated, vanishes after 1 hour."},
{"d100":47,"RESULT":"Your speed is increased by 10 feet for 1 minute."},
{"d100":48,"RESULT":"You gain proficiency on all Strength checks for the next hour, if you don’t already have it."},
{"d100":49,"RESULT":"Your Intelligence is increased by 2 for 1 minute."},
{"d100":50,"RESULT":"One randomly-chosen non-magical item in your possession that weighs 1 pound or less is duplicated."},
{"d100":51,"RESULT":"Mushrooms sprout around you in a 5-foot radius and vanish after 1 minute. If one is harvested and eaten within this time, the creature must make a Constitution saving throw against your spell save DC. On a failed save, it takes 5d6 poison damage. On successful one, it gains 5d6 temporary hit points."},
{"d100":52,"RESULT":"You can smell exceptionally well for 1 minute, gaining blindsight with a radius of 10 feet and advantage on all Perception checks related to odor."},
{"d100":53,"RESULT":"Your feet sink into the ground, making you completely immobile for one minute. This has no effect if you were not standing on the ground when the spell was cast."},
{"d100":54,"RESULT":"One random gem worth 100gp appears near you."},
{"d100":55,"RESULT":"For the next minute, you have double vision. This gives you disadvantage on ranged attacks (including spell attacks) and Perception checks involving sight."},
{"d100":56,"RESULT":"You are surrounded by a faint, pleasant odor. You gain advantage on all Charisma checks you make within the next minute."},
{"d100":57,"RESULT":"You lose proficiency on all skill checks for 1 minute."},
{"d100":58,"RESULT":"You gain freedom of movement for 1 minute."},
{"d100":59,"RESULT":"You gain darkvision with a radius of 60 feet for 1 minute. If you already have darkvision, you lose it for 1 minute."},
{"d100":60,"RESULT":"Approximately 100 gallons of water appear over your head and those within 10 feet of you, evenly distributed above everybody within the radius."},
{"d100":61,"RESULT":"You gain a +1 to your AC for one minute."},
{"d100":62,"RESULT":"You fall victim to a horrible cramp in both legs, reducing your speed by 10 feet for 1 hour."},
{"d100":63,"RESULT":"The next spell you cast within the next hour uses a spell slot of one level lower than what it normally requires. If the spell is a spell of 1st level, you still must expend a spell slot to cast it."},
{"d100":64,"RESULT":"For the next hour, you are unable to read as the letters all appeared jumbled."},
{"d100":65,"RESULT":"For the next day, everything you say must rhyme. If it doesn’t, you take 1d6 psychic damage."},
{"d100":66,"RESULT":"During the next hour, you may re-roll any one save, attack roll, or skill check. If you do, you must take the new roll’s result."},
{"d100":67,"RESULT":"You grow 1d6 inches in height. You gradually return to your original height over the course of 1 day."},
{"d100":68,"RESULT":"You immediately take 2d4 psychic damage."},
{"d100":69,"RESULT":"For the next hour, any time you make an ability check, roll 1d4 and subtract the result."},
{"d100":70,"RESULT":"You gain the ability to speak with animals for one hour."},
{"d100":71,"RESULT":"You get gain a -1 penalty to your AC for 1 minute."},
{"d100":72,"RESULT":"You gain the use of an unseen servant for 1 hour."},
{"d100":73,"RESULT":"The next spell you cast within the hour uses a slot level one level higher than what it normally requires."},
{"d100":74,"RESULT":"A bad joke comes to mind and until you tell it (which takes an entire action), you suffer a Wisdom penalty of 1."},
{"d100":75,"RESULT":"You hear a ringing in your ears for 1 minute. During this time, casting a spell that requires a verbal component requires a Constitution check against your spell save DC."},
{"d100":76,"RESULT":"You lose 1d6x5 pounds. You gradually return to your original weight over the course of 1 day."},
{"d100":77,"RESULT":"Your clothes become dirty and filthy. Until you can change and/or clean your clothes, your Charisma is reduced by 1."},
{"d100":78,"RESULT":"You gain proficiency in Wisdom checks for the next hour, if you don’t already have it."},
{"d100":79,"RESULT":"You shrink 1d6 inches in height. You gradually return to your original height over the course of 1 day."},
{"d100":80,"RESULT":"Your skin permanently darkens as if you have a tan, or if you are already dark-skinned, your skin becomes one shade lighter. A spell such as remove curse can end this effect."},
{"d100":81,"RESULT":"For 1 minute, one creature of your choice within 30 feet of you gains a -1 penalty to attack rolls, damage rolls, and their AC."},
{"d100":82,"RESULT":"For the next hour, any time you make an ability check, roll 1d4 and add the result."},
{"d100":83,"RESULT":"If you cast a spell with a saving throw within the next minute, the target gainsdisadvantage on its saving throw."},
{"d100":84,"RESULT":"Your Strength is increased by 2 for 1 minute."},
{"d100":85,"RESULT":"One creature of your choice gains a +1 bonus to attack rolls, damage rolls, and its AC for 1 minute."},
{"d100":86,"RESULT":"You immediately heal 2d10 hit points."},
{"d100":87,"RESULT":"You gain proficiency on all Intelligence checks for the next hour, if you don’t already have it."},
{"d100":88,"RESULT":"The power of your magic is strong! For the next hour, any spell you cast does not require a verbal component."},
{"d100":89,"RESULT":"You gain 1d6x10 pounds. You gradually return to your original weight over the course of 1 day."},
{"d100":90,"RESULT":"You gain proficiency in all Dexterity checks for the next hour, if you don’t already have it."},
{"d100":91,"RESULT":"Your fingernails and toenails grow to an uncomfortable length. Until you trim them, your Dexterity is reduced by 1 and your speed is reduced by 5 feet, even if you’re not wearing shoes."},
{"d100":92,"RESULT":"You gain the effects of the blur spell for 1 minute, which does not require concentration to maintain."},
{"d100":93,"RESULT":"For the next hour, you appear to others to be the opposite gender."},
{"d100":94,"RESULT":"You gain the service of a 2nd-level spiritual weapon for 1 minute."},
{"d100":95,"RESULT":"The power of your magic is strong! For the next hour, any spell you cast does not require a somatic component."},
{"d100":96,"RESULT":"You gain proficiency in all Constitution checks for the next hour, if you don’t already have it."},
{"d100":97,"RESULT":"Every inanimate object that isn't being worn or carried within 40 feet of you becomes enshrouded with shadows for 1 minute. Enshrouded objects are considered heavily obscured."},
{"d100":98,"RESULT":"Your fingers become sore for 1 hour. During this time, you must succeed on a Dexterity saving throw against your spell save DC to cast a spell with a somatic component."},
{"d100":99,"RESULT":"You feel extremely nauseated. Make a Constitution saving throw against your spell save DC. If you fail, you must spend your next action throwing up."},
{"d100":100,"RESULT":"You immediately lose one unspent sorcery point."}]